"""캐릭터 시드 데이터 - 20캐릭터 4카테고리 (Veo 영상 생성용 신체 특징 포함)"""

from __future__ import annotations

import asyncio
import os

from prisma import Prisma

CHARACTERS = [
    # ===== 밈 / 표정 캐릭터 (MEME) =====
    {
        "name": "아냐 포저",
        "nameEn": "Anya Forger",
        "series": "스파이 패밀리",
        "category": "MEME",
        "description": "분홍 머리, 초록 눈, 작은 체구, 뿔 머리띠",
        "promptFeatures": "tiny girl age 5, shoulder-length pink hair with flower crown wreath on head, extremely large round bright green eyes taking up half the face, small open mouth showing excitement, round chubby cheeks, very small petite body, dark brown school uniform dress with gold cuff bracelets, gold pendant necklace, adorable expressive face, anime style",
        "heightCm": 99,
        "bodyBuild": "매우 작고 마른 어린아이 체형, 짧은 팔다리",
        "faceFeatures": "큰 초록색 둥근 눈, 둥근 얼굴, 작은 코와 입, 분홍색 머리카락 양갈래 번 스타일",
        "costumeDesc": "이든 아카데미 교복 - 검은색 원피스에 하얀 칼라, 빨간 리본",
        "distinctMarks": "뿔 모양 머리띠, 특유의 'ㅎ' 모양 입, 와쿠와쿠 표정",
        "veoPrompt": "99cm petite girl age 5-6, round face, huge green eyes, pink hair in two buns with horn headband, black school dress white collar red ribbon, expressive mischievous face",
        # artStyle(KR): 밝은 파스텔 톤에 부드러운 둥근 외곽선, 캐릭터 눈이 매우 크고 동그란 디포르메 스타일, 깔끔한 디지털 채색에 그림자가 부드러움, WIT Studio 특유의 세밀한 배경과 귀여운 코미디 이펙트, 전체적으로 따뜻하고 밝은 동화책 느낌
        "artStyle": "CloverWorks / WIT Studio Spy x Family style, soft pastel color palette with warm pink and cream tones, clean rounded linework with gentle shading, large expressive deformed chibi-like eyes, polished modern digital coloring with smooth gradient shadows, highly detailed European architecture backgrounds, warm ambient lighting with soft diffused glow, cute comedic visual effects like sparkle eyes and sweat drops, storybook fairy-tale atmosphere with refined modern anime production quality",
        "extraImages": "face_smile.png,face_waku.png,side.png,eating.png,studying.png,waving.png,running.png,jumping.png,reading.png,face_sparkle.png,face_shocked.png,face_angry.png",
        "worldContext": "Cold War-era divided nation Ostania, Eden Academy elite school with Gothic architecture rose gardens and marble hallways, the Forger family warm living room and kitchen, Berlin-inspired European city streets and cafes, beautiful evening cityscape, espionage and spy mission settings, soft warm pastel tones",
        "seriesDescription": "스파이 패밀리는 스파이 아버지(로이드), 살인청부업자 어머니(요르), 독심술 딸(아냐)이 서로의 정체를 숨기며 가짜 가족을 이루는 코미디 액션 만화. 냉전시대 유럽풍 세계관에서 아냐의 학교생활과 가족의 비밀 임무가 유쾌하게 펼쳐진다.",
        "voiceId": "shimmer",
        "voiceStyle": "Cute little girl voice, high-pitched, excited, speaks Korean with childlike lisping and wonder",
        "bodyType": "소녀",
        "primaryColor": "pink",
        "sortOrder": 1,
    },
    {
        "name": "몽키 D. 루피",
        "nameEn": "Monkey D. Luffy",
        "series": "원피스",
        "category": "MEME",
        "description": "검은 짧은 머리, 밀짚모자, 왼쪽 눈 밑 흉터, 빨간 조끼",
        "promptFeatures": "young man age 19, very large perfectly round white eyes with tiny black dot pupils (classic One Piece eye style), short spiky messy black hair poking under large yellow straw hat with red ribbon band, small crescent scar under left eye, huge ear-to-ear toothy grin showing all teeth, open red cardigan vest with gold buttons showing bare chest with large X-shaped scar, blue denim shorts, lean tanned skin, anime style",
        "heightCm": 174,
        "bodyBuild": "마른 근육질, 고무처럼 유연한 몸, 넓은 어깨 대비 가는 허리",
        "faceFeatures": "둥글고 순진한 큰 눈, 왼쪽 눈 밑 초승달 흉터, 항상 활짝 웃는 넓은 입",
        "costumeDesc": "빨간색 오픈 조끼(단추 없이 가슴 드러냄), 파란색 반바지, 고무 샌들",
        "distinctMarks": "밀짚모자(빨간 띠), 왼쪽 눈 밑 흉터, 가슴 X자 큰 흉터",
        "veoPrompt": "174cm lean muscular young man age 19, short messy black hair, crescent scar under left eye, huge grin, straw hat with red band, open red vest showing X-scar on chest, blue shorts, rubber sandals",
        # artStyle(KR): 굵고 과감한 검은 외곽선에 원색 위주의 화려한 채색, 오다 에이이치로 특유의 만화적 과장법, 밝고 에너지 넘치는 소년만화 스타일
        "artStyle": "Toei Animation One Piece modern Wano arc style, bold confident linework with vivid saturated primary colors, clean digital cel-shading with strong rim lighting and warm highlights, Eiichiro Oda's exaggerated expressive faces and dynamic proportions, colorful tropical ocean backgrounds with volumetric sunlight, energetic shonen action composition with natural fluid motion lines, high-contrast warm color grading with orange and blue complementary tones",
        "extraImages": "face_smile.png,face_laugh.png,side.png,eating_meat.png,eating_noodle.png,sitting.png,running.png,jumping.png,sitting_barrel.png,face_grin.png,face_yell.png,face_serious.png",
        "worldContext": "Great Pirate Era Grand Line ocean, Thousand Sunny pirate ship with lion figurehead wooden deck grass lawn Sanji's kitchen and crow's nest, pirate harbor towns and taverns, banquet tables overflowing with meat, tropical islands and beaches, Water Seven floating city, Wano Country Japanese-style castle, Straw Hat crew's free-spirited adventure, bright vivid colorful cartoon world",
        "seriesDescription": "원피스는 고무인간이 된 소년 루피가 해적왕이 되겠다는 꿈을 품고 동료들과 해적단을 꾸려 전설의 보물 원피스를 찾아 대항해시대의 바다를 모험하는 이야기. 각 섬마다 다른 문화와 적이 등장하며, 우정과 자유를 핵심 주제로 한 역대급 장편 소년만화.",
        "voiceId": "echo",
        "voiceStyle": "Energetic teenage boy, loud and cheerful, speaks Korean with carefree enthusiasm and occasional yelling",
        "bodyType": "소년",
        "primaryColor": "red",
        "sortOrder": 2,
    },
    {
        "name": "우즈마키 나루토",
        "nameEn": "Uzumaki Naruto",
        "series": "나루토",
        "category": "MEME",
        "description": "금발 스파이크, 볼 수염 자국 3줄, 주황 점프수트, 이마 보호대",
        "promptFeatures": "young man age 17, tall spiky bright golden blonde hair, vivid cerulean blue eyes with sharp determined look, three thin horizontal whisker-like marks on each cheek, dark blue metal forehead protector with engraved leaf spiral symbol tied on forehead, orange-black zip-up tracksuit jacket with high collar, athletic muscular tanned skin, confident smirk, anime style",
        "heightCm": 180,
        "bodyBuild": "다부진 운동선수 체형, 넓은 어깨, 탄탄한 근육",
        "faceFeatures": "밝은 파란 눈, 양볼에 각 3줄씩 수염 같은 자국, 금발 스파이크 머리, 넓은 이마",
        "costumeDesc": "주황+검정 트랙수트 점프수트, 검은 샌들, 이마에 나뭇잎 마을 금속 보호대",
        "distinctMarks": "양볼 수염 자국 각 3줄, 나뭇잎 이마 보호대, 오른손 붕대",
        "veoPrompt": "180cm athletic young man age 17, spiky blonde hair, blue eyes, three whisker marks each cheek, orange-black tracksuit, metal leaf village forehead protector, determined expression",
        # artStyle(KR): 따뜻한 주황-초록 톤, 차크라 이펙트, 키시모토 특유의 날카로운 눈매, Studio Pierrot 느낌
        "artStyle": "Studio Pierrot Naruto Shippuden style, warm orange-green earth tone palette with golden sunset lighting, sharp angular character designs with Kishimoto's distinctive eye style, detailed ninja village backgrounds blending Japanese traditional architecture with dense forests, dynamic chakra energy effects with blue spirals and orange aura glow, cinematic camera angles with depth of field, modern digital compositing with rich atmospheric haze and dust particles, natural fluid taijutsu combat choreography",
        "extraImages": "face_smile.png,face_grin.png,side.png,eating_ramen.png,training.png,waving.png,running.png,jumping.png,sitting.png,face_determined.png,face_yell.png,face_serious.png",
        "worldContext": "Hidden Leaf Village Konohagakure with Hokage rock mountain ninja academy and red-roofed village panorama, Ichiraku Ramen shop with wooden counter steaming ramen bowls and red noren curtain, Team 7 training ground with three wooden posts and grass field, Valley of the End waterfall, Five Great Ninja Villages, Japanese traditional architecture blended with dense forests, warm orange and green natural tones",
        "voiceId": "echo",
        "voiceStyle": "Hot-blooded teenage boy, determined and loud, speaks Korean with passionate energy and never-give-up spirit",
        "bodyType": "소년",
        "primaryColor": "orange",
        "seriesDescription": "나루토는 부모 없이 마을의 외톨이로 자란 소년 나루토가 최고의 닌자 '호카게'를 꿈꾸며 성장하는 이야기. 체내에 봉인된 구미호의 힘과 끈기로 동료들을 지키며, 닌자 세계의 전쟁과 평화를 그린 대표적 소년만화.",
        "sortOrder": 3,
    },
    {
        "name": "덴지",
        "nameEn": "Denji",
        "series": "체인소 맨",
        "category": "MEME",
        "description": "금발 헝클어진 머리, 가슴에 체인소 시동줄, 마른 체형",
        "promptFeatures": "young man age 16, messy shaggy dirty blonde-orange hair falling over forehead, small tired half-closed yellow-brown eyes, sharp jagged shark-like teeth visible in slight grin, very skinny lanky body with long limbs, wrinkled loose beige dress shirt with rolled-up sleeves, thin black necktie, black dress pants, red-white sneakers, slouching lazy posture, anime style",
        "heightCm": 170,
        "bodyBuild": "마르고 영양실조 느낌의 가는 체형, 뼈가 살짝 보이는 마른 몸",
        "faceFeatures": "날카로운 이빨, 멍한 표정, 헝클어진 더티 블론드 머리, 피곤한 눈",
        "costumeDesc": "하얀 와이셔츠에 검은 넥타이, 검은 바지, 가끔 상의 탈의",
        "distinctMarks": "가슴 중앙 체인소 시동줄 손잡이, 날카로운 송곳니",
        "veoPrompt": "170cm skinny young man age 16, messy dirty blonde hair, tired eyes, sharp jagged teeth, chainsaw pull cord on chest center, wrinkled white shirt loose black tie, black pants, wild expression",
        # artStyle(KR): 어둡고 거친 그리티한 톤, MAPPA 특유의 높은 작화력, 후지모토 타츠키의 영화적 연출
        "artStyle": "MAPPA Chainsaw Man style, dark gritty urban tone with desaturated cool shadows and harsh fluorescent lighting, raw kinetic linework with high-fidelity character animation, Fujimoto Tatsuki's cinematic film-inspired composition with dramatic dutch angles, stark contrast between dark Tokyo backstreet atmosphere and absurdist comedy moments, visceral action sequences with weight and impact, muted color palette punctuated by vivid red blood accents, realistic urban night photography aesthetic with neon reflections",
        "extraImages": "face_smile.png,face_grin.png,side.png,fighting_stance.png,eating.png,sitting.png,fullbody.png,running.png,chainsaw_action.png,face_laugh.png,face_shocked.png,face_angry.png",
        "worldContext": "modern Tokyo where devils exist in everyday life, Public Safety Division office in a worn-down building with fluorescent lights and office desks, Tokyo back alleys and abandoned buildings, destroyed streets from devil attacks, convenience stores and cheap diners, Denji's run-down apartment, dark gritty urban nightscape, brutal yet humorous world of blood and chainsaws, dark tones with vivid red accents",
        "seriesDescription": "체인소맨은 빈곤한 소년 덴지가 체인톱 악마와 합체해 악마 사냥꾼이 되는 다크 액션 만화. 꿈은 소박하게 잘 먹고 여자친구 사귀는 것. 잔혹한 액션과 허탈한 유머, 예측불가한 전개가 특징.",
        "voiceId": "ash",
        "voiceStyle": "Lazy unmotivated teenage boy, low energy mumbling, speaks Korean with rough casual slang",
        "bodyType": "소년",
        "primaryColor": "yellow",
        "sortOrder": 4,
    },
    {
        "name": "이타도리 유지",
        "nameEn": "Itadori Yuji",
        "series": "주술회전",
        "category": "MEME",
        "description": "분홍/갈색 투톤 짧은 머리, 근육질, 파란 후드",
        "promptFeatures": "young man age 15, short spiky undercut hair with vivid salmon-pink top and dark brown buzzed sides, warm determined brown eyes, round friendly face with strong jaw, muscular broad-shouldered athletic build in fighting stance, dark navy blue high-collar jujutsu sorcerer uniform with purple trim lines, red scarf/hood around neck, red sneakers, energetic fighting spirit expression, anime style",
        "heightCm": 173,
        "bodyBuild": "다부진 격투가 체형, 넓은 어깨, 두꺼운 팔뚝, 탄탄한 하체",
        "faceFeatures": "갈색 눈, 짧은 언더컷 - 위는 핑크/아래는 갈색 투톤, 둥근 얼굴형",
        "costumeDesc": "검은색 주술고전 교복 상하의, 빨간 후드 또는 파란 후디",
        "distinctMarks": "분홍+갈색 투톤 헤어, 주술 각성 시 얼굴에 검은 문양",
        "veoPrompt": "173cm muscular young man age 15, undercut hair pink top brown sides, brown eyes, round face, broad shoulders, black high-collar uniform, energetic expression",
        # artStyle(KR): 현대적 세련된 애니 스타일, MAPPA의 3D+2D 혼합, 보라-파란 어두운 색감, 감정이 강렬한 눈
        "artStyle": "MAPPA Jujutsu Kaisen style, sleek modern anime with sharp precise linework and deep purple-blue dark color palette, seamless 2D-3D hybrid animation with dynamic rotating camera work, cursed energy depicted as black smoky tendrils with inner purple glow, intense emotional close-ups with detailed eye reflections, high-contrast lighting between bright modern school scenes and dark ominous domain expansions, fluid martial arts combat with weight and momentum, polished digital compositing with cinematic color grading",
        "extraImages": "fullbody.png,face_smile.png,side_fist.png,fighting_stance.png,eating.png,sitting.png,standing_relax.png,running.png,punch_action.png,face_laugh.png,face_shocked.png,face_serious.png",
        "worldContext": "Tokyo Jujutsu High Japanese-style school building training dojo and wide grounds, modern Tokyo city haunted by curses, Shibuya station underground and bustling district, sorcerer mission sites in abandoned schools hospitals and dark barrier domains, Okinawa beach, high school classrooms and gymnasium, world where bright daily life coexists with dark curses, purple and blue cursed energy effects",
        "seriesDescription": "주술회전은 특급 저주 스쿠나의 손가락을 삼킨 고등학생 유지가 주술사가 되어 저주와 싸우는 다크 배틀 만화. 현대 일본을 배경으로 보이지 않는 저주가 사람을 해치고, 주술사들이 이를 퇴치하는 세계관.",
        "voiceId": "echo",
        "voiceStyle": "Bright athletic teenage boy, warm and upbeat, speaks Korean with friendly casual tone",
        "bodyType": "근육질",
        "primaryColor": "pink",
        "sortOrder": 5,
    },
    # ===== 액션 캐릭터 (ACTION) =====
    {
        "name": "고죠 사토루",
        "nameEn": "Gojo Satoru",
        "series": "주술회전",
        "category": "ACTION",
        "description": "흰 머리, 검은 안대(파란 눈), 키 큼, 검은 교복",
        "promptFeatures": "very tall man age 28, fluffy upswept snow-white spiky hair, brilliant glowing six-eyes blue irises hidden behind sleek black rectangular blindfold covering both eyes, 190cm tall lean model-like proportions with long legs, dark navy-black high-collar zip-up uniform jacket with purple geometric accents, one hand raised with index finger pointing up, handsome sharp angular features, cocky confident smirk, anime style",
        "heightCm": 190,
        "bodyBuild": "장신 마른 근육질, 190cm의 긴 팔다리, 모델 같은 비율",
        "faceFeatures": "눈부시게 밝은 하늘색/파란 눈(육안), 흰색 스파이크 머리, 날카로운 이목구비, 잘생긴 얼굴",
        "costumeDesc": "검은색 하이넥 교복 상하의, 검은 안대(눈 가림), 가끔 선글라스",
        "distinctMarks": "검은 안대로 눈을 가림, 벗으면 빛나는 파란 눈(육안), 190cm 장신",
        "veoPrompt": "190cm tall lean muscular man age 28, white spiky hair, black blindfold over brilliant blue eyes, sharp handsome face, model proportions, black high-collar uniform, cocky smirk",
        # artStyle(KR): MAPPA 극한 작화력, 무한 능력의 보라색 구체, 3D 카메라 회전과 슬로모션, 파란-보라 주조색
        "artStyle": "MAPPA Jujutsu Kaisen premium style, ultra-polished modern anime with crisp sharp linework, Infinity ability rendered as translucent purple distortion spheres with prismatic light refraction, brilliant glowing blue Six Eyes with ethereal luminescence, cinematic 3D camera orbits and slow-motion combat choreography, sleek urban Tokyo backgrounds with modern architectural detail, dominant blue-purple color scheme with cool sophisticated lighting, high-end digital compositing with bokeh depth effects and lens flare",
        "extraImages": "face_finger.png,face_smile.png,side.png,power_blue.png,eating.png,sitting.png,fullbody.png,running.png,jumping.png,face_blindfold.png,face_eyes_reveal.png,infinity_sphere.png",
        "worldContext": "Tokyo Jujutsu High teacher's lounge and hallways, Shibuya Incident ruined bustling district, Unlimited Void purple infinite space domain, Heian era golden age of sorcery flashback, rooftop of high-rise building overlooking Tokyo Tower, buying sweet desserts at a convenience store in casual daily life, relaxed confident atmosphere befitting the strongest sorcerer, vivid blue and purple cursed energy effects",
        "voiceId": "onyx",
        "voiceStyle": "Cool confident adult man, smug and playful, speaks Korean with arrogant charm and teasing tone",
        "bodyType": "장신",
        "primaryColor": "white",
        "seriesDescription": "주술회전의 최강 캐릭터. 주술고전의 선생님으로, 육안(특수한 눈)을 가진 역대 최강의 주술사. 학생들을 가르치며 주술계의 부패를 바꾸려 하지만, 시부야 사변에서 봉인당한다. 여유롭고 장난스러운 성격이지만 전투에선 압도적.",
        "sortOrder": 6,
    },
    {
        "name": "리바이 아커만",
        "nameEn": "Levi Ackerman",
        "series": "진격의 거인",
        "category": "ACTION",
        "description": "검은 짧은 컷, 작은 키, 날카로운 눈, 조사병단 망토",
        "promptFeatures": "short man age 30s, 160cm, jet black straight undercut hair parted in middle falling over narrow sharp intimidating steel-grey eyes, cold stoic expressionless face with sharp jawline, short stature but extremely defined muscles, dark brown cropped military jacket with Wings of Freedom emblem on shoulder, billowing dark green hooded cloak, 3D maneuver gear metal boxes on hips with leather belt harness, holding grappling blade, anime style",
        "heightCm": 160,
        "bodyBuild": "160cm 단신이지만 극도로 단련된 근육, 넓은 어깨, 굵은 팔뚝과 허벅지",
        "faceFeatures": "좁고 날카로운 회색 눈, 무표정, 검은 언더컷 헤어, 날카로운 턱선",
        "costumeDesc": "갈색 조사병단 재킷, 흰 크라바트(목수건), 녹색 자유의 날개 망토, 입체기동장치",
        "distinctMarks": "160cm 단신, 흰 크라바트, 입체기동장치 벨트, 인류 최강 전사",
        "veoPrompt": "160cm short muscular man age 30s, black undercut hair, narrow sharp grey eyes, cold expression, brown military jacket Wings of Freedom, white cravat, green cloak, 3D maneuver gear belts",
        # artStyle(KR): 어둡고 무거운 밀리터리 톤, WIT+MAPPA 혼합 작화, 회색-갈색-카키 군사 색감
        "artStyle": "WIT Studio / MAPPA Attack on Titan style, dark heavy military atmosphere with muted grey-brown-khaki desaturated palette, highly detailed muscle anatomy and leather gear textures with realistic shading, dynamic ODM gear aerial combat with fluid swinging momentum, medieval European walled city backgrounds with weathered stone detail, dramatic overhead and tracking camera angles, heavy atmospheric fog and steam effects, grim photorealistic lighting with overcast skies, tense cinematic composition with strong silhouette contrast",
        "extraImages": "face_arms_crossed.png,face_serious.png,side_cloak.png,action_blade.png,drinking_tea.png,studying.png,fighting_stance.png,action_attack.png,action_gear.png,face_smirk.png,face_glare.png",
        "worldContext": "triple-walled medieval European city of Wall Maria Rose and Sina, Survey Corps headquarters stone castle with stables war room and mess hall, guard posts and cannons atop the walls, vast plains and forests outside the walls where Titans roam, underground city, Trost district streets, ODM gear aerial combat flying between buildings, dark heavy military atmosphere, muted grey and brown tones",
        "voiceId": "onyx",
        "voiceStyle": "Cold stoic adult man, blunt and dry, speaks Korean with minimal emotion and sharp delivery",
        "bodyType": "소형 근육질",
        "primaryColor": "green",
        "seriesDescription": "진격의 거인은 거대한 성벽 안에서 살던 인류가 벽을 부수고 들어온 거인에 맞서 싸우는 다크 판타지. 리바이는 인류 최강 전사로, 조사병단 병장이자 입체기동장치의 달인. 차갑고 결벽증이 있지만 동료를 깊이 아끼는 캐릭터.",
        "sortOrder": 7,
    },
    {
        "name": "에렌 예거",
        "nameEn": "Eren Yeager",
        "series": "진격의 거인",
        "category": "ACTION",
        "description": "갈색 긴 머리(후반), 초록 눈, 조사병단 유니폼",
        "promptFeatures": "young man age 15 (pre-timeskip), short straight dark brown hair with center part reaching below ears, large earnest green-teal eyes, youthful round face, slim average build, tan-brown cropped military jacket with Wings of Freedom shoulder patch, white collared shirt underneath, white pants with brown leather belt straps, tall brown boots, neutral serious expression, anime style",
        "heightCm": 183,
        "bodyBuild": "183cm 마른 근육질, 긴 팔다리, 후반부 더 단단해진 체형",
        "faceFeatures": "강렬한 초록색 눈, 긴 갈색 머리(만두 묶음), 날카로운 이목구비, 결의에 찬 표정",
        "costumeDesc": "갈색 조사병단 재킷, 흰 바지, 갈색 롱부츠, 입체기동장치 벨트",
        "distinctMarks": "강렬한 초록 눈빛, 후반부 긴 머리 묶음, 손바닥 자해 흉터(거인화용)",
        "veoPrompt": "183cm lean muscular young man age 19, long dark brown hair in messy bun, fierce green eyes, sharp angular face, brown military jacket Wings of Freedom, white pants, brown boots, brooding expression",
        # artStyle(KR): 어둡고 무거운 밀리터리 톤, WIT+MAPPA, 종말론적 분위기, 회색 하늘과 황토색 대지
        "artStyle": "WIT Studio / MAPPA Attack on Titan style, dark apocalyptic atmosphere with grey overcast skies and ochre earth tones, realistic human proportions with detailed expressive face acting, Titan transformation with intense lightning strikes and billowing steam effects, increasingly darker desaturated color grading in later arcs, cinematic wide shots of desolate landscapes and ruined cities, WIT's dynamic tracking shots blended with MAPPA's nuanced emotional close-ups, heavy dramatic shadows with rim lighting on characters",
        "extraImages": "fullbody.png,face_serious.png,side.png,action_blade.png,face_determined.png,sitting.png,running.png,fighting_stance.png,action_attack.png,face_smile.png,face_yell.png,face_angry.png",
        "worldContext": "triple-walled medieval European city and marketplace, Survey Corps barracks with wooden bunk beds and dining hall, Shiganshina frontier district, ruins and forests of Titan territory beyond the walls, Marley nation's modern harbor city Liberio, Paradis Island coastline, ODM gear combat and Titan transformation, world of struggle for freedom, grey overcast skies and ochre earth",
        "voiceId": "ash",
        "voiceStyle": "Intense determined young man, passionate and angry, speaks Korean with fierce conviction",
        "bodyType": "근육질",
        "primaryColor": "brown",
        "seriesDescription": "진격의 거인의 주인공. 어머니를 거인에게 잃고 거인을 모두 구축하겠다고 맹세한 소년. 자신도 거인으로 변신하는 능력을 갖게 되며, 이야기가 진행될수록 자유의 의미와 전쟁의 비극을 다루는 복잡한 캐릭터.",
        "sortOrder": 8,
    },
    {
        "name": "카마도 탄지로",
        "nameEn": "Kamado Tanjiro",
        "series": "귀멸의 칼날",
        "category": "ACTION",
        "description": "적갈색 머리, 이마 흉터/자국, 큰 귀걸이, 녹흑 격자 하오리",
        "promptFeatures": "young man age 15, short wavy dark reddish-burgundy hair with bright red gradient tips swept to the right, large gentle warm burgundy-red eyes with kind expression, prominent dark red burn scar covering left forehead and reaching to eyebrow, small hanafuda flower card earrings dangling from both ears, open green-and-black checkered square pattern haori coat, black demon slayer uniform underneath with white belt, white leg wrappings, brown boots, holding katana sword, determined gentle smile, anime style",
        "heightCm": 165,
        "bodyBuild": "165cm 균형 잡힌 소년 체형, 검술 수련으로 다져진 탄탄한 몸",
        "faceFeatures": "적갈색(버건디) 짧은 머리, 이마 왼쪽 큰 흉터/화상 자국, 붉은 갈색 부드러운 눈, 선한 표정",
        "costumeDesc": "녹색+검정 바둑판 격자무늬 하오리(겉옷), 검은 대원복, 등에 나무상자",
        "distinctMarks": "이마 왼쪽 큰 흉터, 해바라기 카드(하나후다) 귀걸이, 등에 네즈코 상자",
        "veoPrompt": "165cm young man age 15, dark reddish-burgundy hair with red tips, burn scar on left forehead, gentle brown eyes, green-black checkered haori over black uniform, hanafuda earrings, wooden box on back",
        # artStyle(KR): ufotable 극한 영상미, 물의 호흡 파란 물결, CG+2D 융합, 다이쇼 시대 일본 배경
        "artStyle": "ufotable Demon Slayer style, breathtaking visual quality with seamless CG-2D hybrid animation, Water Breathing swordsmanship depicted as flowing translucent blue wave effects wrapping around the blade, Fire Dance energy as vivid crimson flame particles, intricately detailed traditional Japanese textile patterns on kimono and haori, Taisho-era mountain villages and forests as backgrounds, predominantly nighttime scenes with beautiful moonlight and warm lantern illumination, rich volumetric lighting with god rays through trees, fluid graceful sword combat choreography with natural body weight",
        "extraImages": "fullbody.png,face_smile.png,side.png,action_water.png,eating.png,sitting.png,walking_box.png,fighting_stance.png,action_slash.png,face_serious.png,face_determined.png,face_fire.png",
        "worldContext": "Taisho era 1912-1926 Japan, Tanjiro family mountain cabin with snow-covered peaks and charcoal kiln, Demon Slayer Corps Butterfly Mansion with tatami treatment rooms and garden, Mugen Train steam locomotive interior with red seats, Entertainment District Yoshiwara with ornate lanterns and red-lit streets, Swordsmith Village with hot springs and misty mountains, wisteria-covered Final Selection mountain, traditional Japanese architecture and bamboo forests, purple and water-blue effects",
        "voiceId": "coral",
        "voiceStyle": "Kind gentle teenage boy, warm and sincere, speaks Korean with polite earnest tone",
        "bodyType": "소년",
        "primaryColor": "green",
        "seriesDescription": "귀멸의 칼날은 가족을 귀신에게 잃은 소년 탄지로가 귀신이 되어버린 여동생 네즈코를 인간으로 되돌리기 위해 귀살대(귀신 사냥꾼)가 되어 싸우는 이야기. 다이쇼 시대 일본을 배경으로 검술과 호흡법으로 귀신을 베는 화려한 액션이 특징.",
        "sortOrder": 9,
    },
    {
        "name": "쿠로사키 이치고",
        "nameEn": "Kurosaki Ichigo",
        "series": "블리치",
        "category": "ACTION",
        "description": "주황 스파이크 머리, 키 큼, 검은 사신 복장(시해)",
        "promptFeatures": "tall young man age 17, wild tall spiky bright orange hair glowing with highlights, intense narrow brown eyes with heavy brow perpetual scowl, tall 181cm lean muscular build, glowing spiritual energy aura around hands, serious fierce annoyed expression, anime style",
        "heightCm": 181,
        "bodyBuild": "181cm 장신 마른 근육질, 긴 팔다리, 전투형 체형",
        "faceFeatures": "밝은 주황색 스파이크 머리, 갈색 눈, 항상 찡그린 표정, 날카로운 이목구비",
        "costumeDesc": "검은색 사신 복장(시하쿠쇼) - 검은 기모노+하카마, 흰 띠, 등에 거대한 참월도",
        "distinctMarks": "눈에 띄는 주황 머리, 등의 거대한 참월도(잔파쿠토), 항상 찡그린 표정",
        "veoPrompt": "181cm tall lean muscular young man age 17, spiky bright orange hair, brown eyes perpetual scowl, black shinigami robe kimono and hakama white obi, massive cleaver sword on back",
        # artStyle(KR): Studio Pierrot 셀 애니메이션, 참월도의 검은 영압 이펙트, 사신 검정+주황 머리 대비
        "artStyle": "Studio Pierrot Bleach Thousand Year Blood War modern style, bold confident linework with high-contrast black shinigami robes against bright orange hair, dark spiritual pressure rendered as black-red energy arcs with blue light streaks cutting across the frame, clean modern digital cel-shading with dramatic rim lighting, dual-world aesthetic blending white traditional Japanese castle architecture of Soul Society with modern Japanese school settings, striking color contrast composition, fluid powerful sword combat with natural follow-through momentum, cinematic widescreen framing with depth",
        "extraImages": "action_sword.png,face_serious.png,side.png,action_slash.png,eating.png,sitting.png,fullbody.png,running.png,action_attack.png,face_smile.png,face_yell.png,face_hollow_mask.png",
        "worldContext": "Karakura Town modern Japanese residential streets and Kurosaki Clinic, Soul Society Seireitei white-walled Japanese castle city with 13 Court Guard Squad barracks and cherry blossom gardens, Hueco Mundo endless desert under a white moon, Fake Karakura Town battlefield, Wandenreich massive crystal palace, Soul Reaper butterflies and spiritual pressure effects, atmosphere blending Japanese tradition with spirit world, black and white contrast with blue reiatsu energy",
        "voiceId": "ash",
        "voiceStyle": "Grumpy tough teenage boy, irritated but caring, speaks Korean with reluctant cool attitude",
        "bodyType": "장신",
        "primaryColor": "orange",
        "seriesDescription": "블리치는 유령을 볼 수 있는 고등학생 이치고가 사신(죽은 영혼을 인도하는 존재)의 힘을 얻어 악령 할로우와 싸우는 소년만화. 현실 세계와 영혼 세계(소울 소사이어티)를 오가며, 거대한 검으로 싸우는 화려한 배틀이 특징.",
        "sortOrder": 10,
    },
    # ===== 귀여운 캐릭터 (CUTE) =====
    {
        "name": "피카츄",
        "nameEn": "Pikachu",
        "series": "포켓몬",
        "category": "CUTE",
        "description": "노란 몸, 빨간 볼, 번개 꼬리, 뾰족한 귀(검은 끝)",
        "promptFeatures": "small chubby yellow electric mouse creature, bright yellow fur, two red circular cheek pouches, large perfectly round shiny black eyes, small triangular black nose, wide happy open mouth, long pointed ears with black tips, zigzag lightning bolt shaped flat yellow tail with brown base, two brown horizontal stripes on back, short stubby arms and feet with no fingers, round plump body, cheerful excited pose, anime style",
        "heightCm": 40,
        "bodyBuild": "40cm 작고 통통한 설치류 체형, 짧은 팔다리, 둥근 몸통",
        "faceFeatures": "큰 둥근 검은 눈, 빨간 동그란 볼 주머니, 작은 입, 뾰족한 귀(끝이 검은색)",
        "costumeDesc": "없음 - 노란색 털이 전신을 덮음, 갈색 줄무늬가 등에 2개",
        "distinctMarks": "번개 모양 꼬리(노란색), 빨간 볼, 뾰족한 귀 검은 끝",
        "veoPrompt": "40cm chubby yellow rodent, round body, big black eyes, red cheek pouches, pointed ears black tips, lightning bolt tail brown base, two brown back stripes, yellow fur, cheerful expression",
        # artStyle(KR): 단순하고 깔끔한 외곽선, 밝은 원색, 둥글고 귀여운 디포르메, 밝고 건강한 어린이 애니 느낌
        "artStyle": "OLM Inc modern Pokemon anime style, clean simple rounded linework with bright cheerful primary colors, adorable deformed character proportions universally appealing to all ages, vibrant sunlit natural landscapes with lush green meadows forests and beaches, electric spark effects rendered as crisp yellow lightning bolts with white glow, warm natural outdoor lighting with soft cloud shadows, friendly wholesome children's animation aesthetic with polished modern digital coloring and smooth gradient shading",
        "extraImages": "face_smile.png,face_happy.png,face_wink.png,side.png,eating.png,sleeping.png,running.png,jumping.png,action_thunder.png,sitting.png,waving.png,dancing.png,face_angry.png,face_surprised.png,face_love.png,face_cry.png,face_cool.png",
        "worldContext": "Pokemon world Kanto region, green grassy meadows and tall grass patches where wild Pokemon appear, Pokemon Center with red roof and Nurse Joy counter, Pokemon Gym battle field, Professor Oak's laboratory, running alongside Ash on his shoulder, beaches and flower fields, campfire under starry sky, bright cheerful natural scenery, lively yellow and green color palette",
        "voiceId": "shimmer",
        "voiceStyle": "Tiny cute creature, very high-pitched squeaky, speaks Korean in adorable short phrases with bright energy",
        "bodyType": "동물",
        "primaryColor": "yellow",
        "seriesDescription": "포켓몬은 다양한 몬스터(포켓몬)를 잡아 훈련시키고 배틀하는 세계관의 이야기. 피카츄는 주인공 사토시의 파트너 전기 타입 포켓몬으로, 세계에서 가장 유명한 캐릭터 중 하나. 10만볼트 전기 공격이 특기.",
        "sortOrder": 11,
    },
    {
        "name": "카마도 네즈코",
        "nameEn": "Kamado Nezuko",
        "series": "귀멸의 칼날",
        "category": "CUTE",
        "description": "긴 검은 머리(분홍 끝), 입에 대나무, 분홍 기모노",
        "promptFeatures": "young girl age 14, very long straight black hair reaching below waist with gradient orange-pink tips at the ends, large round bright pink eyes with vertical slit demon pupils, small green bamboo muzzle/gag held in mouth by red string, small round gentle face, petite slender body, pink kimono with geometric hemp leaf (asanoha) pattern, dark maroon-checkered obi belt, white haori jacket with pink lining draped over shoulders, dark leg wrappings, wooden geta sandals, gentle shy expression, anime style",
        "heightCm": 153,
        "bodyBuild": "153cm 작고 가냘픈 소녀 체형, 가는 허리, 작은 체구",
        "faceFeatures": "분홍색 세로 동공 눈, 긴 검은 머리(끝이 주황-분홍), 입에 대나무 재갈, 작은 얼굴",
        "costumeDesc": "분홍색 마 잎 무늬 기모노, 검은색+주황색 안감 하오리, 분홍 띠, 나무 게타",
        "distinctMarks": "입에 물고 있는 대나무 재갈, 머리 끝 주황-분홍 그라데이션, 분홍 눈",
        "veoPrompt": "153cm petite girl age 14, long black hair with orange-pink gradient tips, pink slit-pupil eyes, bamboo muzzle in mouth, pink kimono hemp leaf pattern, black haori orange lining, wooden geta",
        # artStyle(KR): ufotable 극한 영상미, 폭혈 분홍 불꽃, 마잎 무늬 세밀 묘사, 분홍-주황+달빛 푸른 조명
        "artStyle": "ufotable Demon Slayer style, stunning visual quality with Nezuko's Blood Demon Art depicted as beautiful luminous pink flame particles, intricate hemp leaf pattern on kimono rendered with fine textile detail, bamboo muzzle carefully detailed, demon mode with mystical vertical slit pupils and ethereal forehead horn, warm pink-orange color palette coexisting with cool blue moonlit illumination, gorgeous nighttime scenes with volumetric fog and soft bokeh, graceful fluid kick-based combat with natural weight and feminine elegance",
        "extraImages": "fullbody.png,face_smile.png,side.png,action_fire.png,eating.png,sitting_box.png,walking.png,sitting.png,action_kick.png,face_determined.png,face_demon.png",
        "worldContext": "Taisho era Japan, bamboo box carried on Tanjiro's back where she sleeps during daytime, Butterfly Mansion tatami rooms and garden, Mugen Train passenger car interior, Entertainment District Yoshiwara glamorous streets with floral kimono and lanterns, wisteria flower field under sunlight, nighttime forest bathed in moonlight, warm protective atmosphere of guarding her brother, pink Blood Demon Art fire effects with warm color palette",
        "voiceId": "nova",
        "voiceStyle": "Quiet gentle girl, soft muffled voice, speaks Korean in very short shy whispers",
        "bodyType": "소녀",
        "primaryColor": "pink",
        "seriesDescription": "귀멸의 칼날의 히로인이자 탄지로의 여동생. 귀신에게 물려 귀신이 되었지만 인간의 마음을 잃지 않은 유일한 존재. 낮에는 대나무 상자에서 잠자고, 밤에는 오빠를 지키며 싸운다. 입에 물고 있는 대나무 재갈이 트레이드마크.",
        "sortOrder": 12,
    },
    {
        "name": "토토로",
        "nameEn": "Totoro",
        "series": "이웃집 토토로",
        "category": "CUTE",
        "description": "회색 큰 몸, 둥근 배, 큰 입, 뾰족한 귀, 짧은 꼬리",
        "promptFeatures": "massive round egg-shaped grey forest spirit creature, dark grey fur on top and sides, large cream-yellow belly with dark grey chevron/arrow pattern markings, huge wide mouth stretching ear to ear, large round white eyes with small black pupils, long grey whiskers, two tall pointed cat-like ears on top, tiny stubby arms with grey claws, short stubby legs, small pointed tail, sitting next to small child with straw hat, gentle calm expression, Studio Ghibli anime style",
        "heightCm": 200,
        "bodyBuild": "200cm 거대한 둥근 체형, 배가 크고 볼록한 달걀형, 짧은 팔다리",
        "faceFeatures": "거대한 둥근 눈(흰자 많음), 넓은 입(귀까지 찢어진), 둥근 코, 긴 수염",
        "costumeDesc": "없음 - 회색 털이 전신을 덮음, 배는 흰색/크림색에 갈색 V자 무늬",
        "distinctMarks": "거대한 둥근 몸, 배의 V자 무늬, 뾰족한 큰 귀, 우산 들기",
        "veoPrompt": "200cm massive round grey forest spirit, egg-shaped body, white belly grey chevron markings, huge mouth ear to ear, round white eyes, pointed ears, stubby limbs, short tail, grey fur, holding leaf umbrella",
        # artStyle(KR): 미야자키 하야오 수채화풍, 붓 터치 살아있는 부드러운 외곽선, 풍경화 같은 배경, 지브리 서정적 분위기
        "artStyle": "Studio Ghibli Hayao Miyazaki style, warm watercolor-inspired color palette with visible soft brushstroke textures, gentle rounded linework with organic hand-drawn quality, extraordinarily detailed painted landscape backgrounds depicting every individual leaf and grass blade swaying in the wind, simple rounded character designs contrasting richly detailed nature environments, green-brown-sky blue natural color harmony, nostalgic warm ambient lighting with golden hour glow, serene lyrical Ghibli atmosphere with gentle wind animation and floating cloud movement",
        "extraImages": "fullbody.png,face_smile.png,side.png,umbrella.png,eating.png,sitting.png,walking.png,dancing.png,playing_ocarina.png,face_surprised.png,face_yell.png,face_laugh.png",
        "worldContext": "1950s rural Japanese village in Saitama prefecture, Satsuki and Mei's old wooden house with creaky floors and dusty attic, giant camphor tree with hollow where Totoro lives, rainy bus stop with red umbrella and Catbus, rice paddies and streams, summer fields with rice stalks swaying in the breeze, starry night sky, Ghibli signature warm nostalgic natural countryside scenery, green and earthy watercolor tones",
        "voiceId": "fable",
        "voiceStyle": "Deep rumbling gentle giant, slow and warm, speaks Korean with low calm comforting tone",
        "bodyType": "대형 동물",
        "primaryColor": "grey",
        "seriesDescription": "이웃집 토토로는 시골로 이사 온 두 자매가 숲속의 거대한 정령 토토로를 만나 신비로운 경험을 하는 이야기. 스튜디오 지브리의 대표작으로, 일본 시골의 자연과 어린 시절의 순수함을 그린 따뜻한 판타지. 토토로는 회색 거대 생물로 우산을 좋아한다.",
        "sortOrder": 13,
    },
    {
        "name": "도라에몽",
        "nameEn": "Doraemon",
        "series": "도라에몽",
        "category": "CUTE",
        "description": "파란 둥근 몸, 흰 배, 빨간 코, 목에 방울, 동그란 손",
        "promptFeatures": "round spherical blue robotic cat, bright blue body, white round face and white belly area, large oval white eyes with small black dot pupils looking upward happily, small round red nose in center, wide open laughing mouth showing red tongue, six long black whiskers three on each side, no ears (flat round head), red collar with large round golden yellow bell hanging, round white sphere hands without any fingers, short stubby blue legs, semi-circular 4D pocket on white belly, cheerful laughing pose, classic Fujiko anime style",
        "heightCm": 129,
        "bodyBuild": "129cm 둥글고 통통한 로봇 고양이 체형, 짧은 팔다리, 완벽한 구 형태",
        "faceFeatures": "큰 둥근 흰 눈(검은 점 눈동자), 빨간 둥근 코, 흰 얼굴, 긴 수염 6개",
        "costumeDesc": "없음 - 파란 외피가 전신, 흰 배, 빨간 목걸이에 노란 방울, 배에 4D주머니",
        "distinctMarks": "귀 없음(쥐가 갉아먹음), 4D주머니, 빨간 코, 노란 방울, 동그란 흰 손",
        "veoPrompt": "129cm round blue robotic cat, spherical body, white face and belly, round white eyes black pupils, red nose, six whiskers, no ears, red collar yellow bell, 4D pocket on belly, round white fingerless hands",
        # artStyle(KR): 후지코 F. 후지오 극도로 단순한 둥근 외곽선, 원과 타원의 미니멀 디자인, 밝은 원색, 어린이 만화 느낌
        "artStyle": "Shin-Ei Animation modern Doraemon style, extremely simple clean rounded outlines with minimalist circle-and-oval character construction, bright flat primary colors of blue white and red with smooth digital coloring, clean simplified Japanese suburban neighborhood and school backgrounds, cheerful friendly children's cartoon aesthetic with warm inviting atmosphere, future gadgets appearing with sparkling light effects and magical glow, soft even lighting with gentle pastel highlights, approachable timeless character design with modern production polish",
        "extraImages": "face_smile.png,face_happy.png,face_wink.png,side.png,eating.png,sleeping.png,running.png,jumping.png,action_pocket.png,sitting.png,waving.png,dancing.png,face_angry.png,face_surprised.png,face_love.png,face_cry.png,face_cool.png,fullbody.png",
        "worldContext": "modern Tokyo suburban residential neighborhood, Nobita's second-floor bedroom with desk and time machine emerging from closet, vacant lot on the hill with three concrete pipes as playground hangout, school classroom and schoolyard, 22nd century future department store, wonderful gadgets from 4D pocket like bamboo copter and Anywhere Door, ordinary warm Japanese suburban daily life atmosphere, bright simple pastel colors",
        "voiceId": "coral",
        "voiceStyle": "Friendly round robot, slightly nasal mid-pitch, speaks Korean with patient helpful explanations",
        "bodyType": "로봇",
        "primaryColor": "blue",
        "seriesDescription": "도라에몽은 22세기 미래에서 온 고양이형 로봇이 무능한 소년 노비타를 도와주는 일본 국민 만화. 배에 달린 4차원 주머니에서 어디로든 문, 타임머신 등 신기한 미래 도구를 꺼내 문제를 해결한다. 50년 넘게 사랑받는 일본 대표 캐릭터.",
        "sortOrder": 14,
    },
    {
        "name": "토니토니 쵸파",
        "nameEn": "Tony Tony Chopper",
        "series": "원피스",
        "category": "CUTE",
        "description": "작은 순록, 갈색 털, 분홍 모자(X표시), 파란 코",
        "promptFeatures": "tiny adorable reindeer creature standing upright on two legs, round chubby light brown fur body, very large round shiny black eyes with innocent look, small bright blue round nose, wide happy open mouth, two small brown antler horns poking out from sides of oversized pink top hat with large white X cross mark on front, red ribbon tied around hat, wearing small red shorts, tiny hooves as hands, short stubby legs, happy cute excited expression, One Piece anime style",
        "heightCm": 90,
        "bodyBuild": "90cm 작은 순록이 직립한 체형, 둥글고 통통, 짧은 팔다리",
        "faceFeatures": "큰 둥근 눈, 파란색 코(특이한 코), 갈색 털, 작은 뿔 2개",
        "costumeDesc": "분홍색 큰 실크햇(흰 X자 표시), 빨간 반바지, 가끔 배낭",
        "distinctMarks": "파란 코, 분홍 X표시 모자, 작은 순록 뿔, 직립 보행",
        "veoPrompt": "90cm small reindeer standing upright, round chubby light brown fur body, big innocent eyes, blue nose, small antlers, oversized pink top hat white X mark, red shorts",
        # artStyle(KR): 오다 에이이치로의 굵은 외곽선, 둥글고 귀여운 디포르메 마스코트, 밝고 에너지 넘치는 스타일+귀여움
        "artStyle": "Toei Animation One Piece modern style, bold outlines with bright vivid primary colors, Chopper drawn with extra-round adorable mascot-like deformed proportions, exaggerated star-eyes and heart-eyes comedic expression effects, warm cheerful lighting with tropical ocean and colorful pirate ship backgrounds, cute character animation with bouncy natural movement, Oda's signature joyful energetic shonen aesthetic combined with enhanced cuteness and warmth, clean modern digital coloring with soft gradient shadows",
        "extraImages": "face_smile.png,face_happy.png,side.png,eating.png,reading.png,sleeping.png,running.png,jumping.png,action_doctor.png,sitting.png,waving.png,dancing.png,face_shy.png,face_surprised.png,face_angry.png,fullbody.png",
        "worldContext": "Great Pirate Era Grand Line ocean, Thousand Sunny infirmary with medicine shelves small bed and cherry blossom curtains, Sunny's deck and grass lawn, Drum Kingdom snow-covered mountains and Hiluluk's cherry blossoms, pirate harbor town marketplace and fruit stalls, tropical island beach, adventuring alongside Luffy, warm world of a cute little reindeer doctor, bright vivid colors with pink cherry blossom effects",
        "voiceId": "shimmer",
        "voiceStyle": "Tiny timid creature, high-pitched nervous, speaks Korean with shy stuttering and occasional bravery",
        "bodyType": "동물",
        "primaryColor": "brown",
        "seriesDescription": "원피스에 등장하는 밀짚모자 해적단의 의사. 원래는 순록이지만 악마의 열매를 먹고 인간처럼 걷고 말할 수 있게 됨. 작고 귀엽지만 뛰어난 의술 실력을 가졌고, 변신 능력으로 전투에도 참여. 루피를 선장으로 따르며 만능약을 만드는 것이 꿈.",
        "sortOrder": 15,
    },
    # ===== 인기 미남/미소녀 (BEAUTY) =====
    {
        "name": "렘",
        "nameEn": "Rem",
        "series": "리제로",
        "category": "BEAUTY",
        "description": "파란 짧은 머리(한쪽 눈 가림), 메이드복, 파란 눈",
        "promptFeatures": "young woman age 18, short chin-length light sky-blue hair with right side swept over completely covering right eye, visible left eye is large round bright blue, small delicate round face with soft gentle expression, petite slender body, black-and-white French maid dress with puffy short sleeves, white frilly apron over black skirt, white maid headdress/headband with blue ribbon, white thigh-high stockings, black mary-jane shoes, multiple character reference poses shown, anime style",
        "heightCm": 154,
        "bodyBuild": "154cm 가냘프고 슬림한 소녀 체형, 가는 허리, 작은 체구",
        "faceFeatures": "짧은 하늘색/파란 머리(오른쪽 눈 가림), 보이는 왼쪽 파란 눈, 작고 귀여운 얼굴",
        "costumeDesc": "흑백 메이드복 - 검은 원피스, 흰 에이프런, 흰 머리 장식(프릴), 파란 리본",
        "distinctMarks": "한쪽 눈을 가리는 파란 앞머리, 메이드 헤드드레스, 쌍둥이(람의 자매)",
        "veoPrompt": "154cm petite slender woman age 18, short light blue hair covering right eye, left blue eye visible, gentle expression, black-white maid uniform white apron, frilly headdress blue ribbon",
        # artStyle(KR): 라이트노벨 삽화풍 섬세하고 투명한 채색, 파란-보라 파스텔, 세밀한 프릴/레이스, 몽환적 이세계 판타지
        "artStyle": "White Fox Re:Zero style, delicate light novel illustration aesthetic with translucent luminous coloring, blue-purple pastel tone dominant palette with ethereal glow, extremely detailed hair strands and maid uniform frill and lace textures, morning star weapon combat with swirling wind and ice crystal effects, ornate European mansion interior backgrounds with crystal chandeliers and rich fabric textures, clean dreamy isekai fantasy atmosphere with soft diffused lighting, gentle bloom and light scatter effects creating otherworldly mood",
        "extraImages": "face_smile.png,face_shy.png,side.png,eating.png,cleaning.png,sitting.png,running.png,action_morningstar.png,face_determined.png,fullbody.png",
        "worldContext": "medieval European-style isekai Kingdom of Lugnica, Roswaal Mansion grand Western hallways with crystal chandeliers and spacious kitchen and laundry room, Arlam Village stone-wall paths and thatched-roof cottages, Royal Capital Lugnica walled city and royal selection stage, Sanctuary witch's tomb and fog-shrouded forest, Rem and Ram twin maids devoted daily life, fantasy world with magic and demon beasts, mystical blue and purple toned atmosphere",
        "voiceId": "nova",
        "voiceStyle": "Devoted gentle young woman, soft and caring, speaks Korean with polite devoted warmth",
        "bodyType": "소녀",
        "primaryColor": "blue",
        "seriesDescription": "리제로(Re:Zero)는 편의점에서 이세계로 소환된 소년 스바루가 죽을 때마다 특정 시점으로 되돌아가는 능력으로 소중한 사람들을 구하려는 이야기. 렘은 로즈월 저택의 쌍둥이 메이드 중 동생으로, 스바루를 깊이 사랑하는 헌신적 캐릭터. 메이드복 차림이지만 전투력도 강하다.",
        "sortOrder": 16,
    },
    {
        "name": "아스나",
        "nameEn": "Asuna Yuuki",
        "series": "소드 아트 온라인",
        "category": "BEAUTY",
        "description": "긴 갈색/주황 머리, 흰-빨간 기사 복장, 슬림 체형",
        "promptFeatures": "young woman age 18, very long flowing chestnut-orange hair reaching below waist with small braid on left side, large warm golden-hazel eyes, elegant beautiful oval face, slender athletic body with long legs, white sleeveless top with red trim, red pleated mini skirt, grey thigh-high stockings, red knee-high boots, white detached sleeves, holding thin rapier sword, confident graceful battle stance, anime style",
        "heightCm": 168,
        "bodyBuild": "168cm 슬림하고 날씬한 체형, 긴 다리, 우아한 비율",
        "faceFeatures": "긴 밤색-주황색 스트레이트 머리(허리까지), 헤이즐/갈색 눈, 아름다운 이목구비",
        "costumeDesc": "흰+빨간 혈맹기사단 유니폼 - 흰 브레스트플레이트, 빨간 미니스커트, 흰 부츠",
        "distinctMarks": "허리까지 오는 긴 밤색 머리, 레이피어 검, 우아하고 강인한 분위기",
        "veoPrompt": "168cm slender athletic woman age 18, long chestnut-orange hair to waist, hazel eyes, elegant features, white-red knight uniform chest plate, red mini skirt, white knee boots, rapier sword",
        # artStyle(KR): A-1 Pictures 밝고 투명한 채색, 빛나는 검 궤적, 아인크라드 판타지 배경, 금색-흰색 판타지 로맨스
        "artStyle": "A-1 Pictures Sword Art Online Alicization style, bright luminous light novel illustration coloring with clean polished digital linework, Sword Skills rendered as radiant golden-orange light trail arcs following the rapier blade, beautiful medieval fantasy architecture and sunlit green meadow backgrounds of Aincrad, detailed flowing hair animation with natural wind physics, warm golden-white fantasy romance color palette with lens flare highlights, elegant graceful fencing combat with fluid natural body movement, soft bloom lighting creating magical virtual world atmosphere",
        "extraImages": "face_smile.png,face_happy.png,fullbody.png,side.png,eating.png,sitting.png,running.png,action_sword.png,action_rapier.png,face_blush.png,face_determined.png,face_angry.png,face_gentle.png",
        "worldContext": "virtual reality VRMMORPG Aincrad 100-floor iron castle with different themed floors of meadows deserts and glaciers, Floor 22 forest cabin home of Kirito and Asuna's log cottage, Floor 1 Town of Beginnings medieval walled city with NPC shops, boss rooms with massive stone chambers and glowing magic circles, ALO fairy world treehouse cities, real-world Tokyo hospitals and schools, sword and magic fantasy blended with futuristic technology, bright golden and white light effects",
        "voiceId": "nova",
        "voiceStyle": "Elegant confident young woman, clear and strong, speaks Korean with graceful authority",
        "bodyType": "슬림",
        "primaryColor": "white",
        "seriesDescription": "소드 아트 온라인(SAO)은 VR 게임에 갇힌 1만 명의 플레이어가 게임을 클리어하지 못하면 현실에서도 죽는 데스게임에 빠지는 이야기. 아스나는 게임 속 최강 여검사이자 주인공 키리토의 연인. 우아하고 강인하며 요리 실력도 뛰어나다.",
        "sortOrder": 17,
    },
    {
        "name": "미카사 아커만",
        "nameEn": "Mikasa Ackerman",
        "series": "진격의 거인",
        "category": "BEAUTY",
        "description": "검은 짧은 머리(후반), 목 빨간 머플러, 근육질, 조사병단 유니폼",
        "promptFeatures": "young woman age 19, short chin-length straight black bob-cut hair, narrow serious dark grey eyes with stoic cold expression, beautiful but stern face, toned athletic muscular body 170cm, dark red/maroon scarf wrapped around neck, tan-brown cropped military Survey Corps jacket with Wings of Freedom shoulder patch, white shirt underneath, white pants with brown leather belt straps and 3D maneuver gear harness, tall brown knee-high boots, hand on hip confident pose, anime style",
        "heightCm": 170,
        "bodyBuild": "170cm 탄탄한 근육질 여성 체형, 복근이 보이는 단련된 몸, 넓은 어깨",
        "faceFeatures": "짧은 검은 단발(보브컷), 짙은 회색 눈, 날카롭고 아름다운 이목구비, 무표정",
        "costumeDesc": "갈색 조사병단 재킷, 흰 바지, 갈색 부츠, 입체기동장치 벨트, 목에 빨간 머플러",
        "distinctMarks": "목에 항상 두른 빨간 머플러(에렌에게 받은), 무표정하지만 아름다운 얼굴",
        "veoPrompt": "170cm toned muscular woman age 19, short black bob-cut hair, deep grey eyes, stoic stern expression, brown Survey Corps jacket Wings of Freedom, white pants, brown boots, 3D gear belts, red scarf around neck",
        # artStyle(KR): 어둡고 무거운 밀리터리 톤, 미카사의 근육+입체기동장치 사실적 표현, 빨간 머플러만 선명한 대비
        "artStyle": "WIT Studio / MAPPA Attack on Titan style, dark heavy military atmosphere with detailed muscle definition and realistic 3D maneuver gear rendering, dynamic aerial flight action sequences with natural swinging physics, emotional cinematic close-up shots with nuanced facial expression, iconic red scarf fluttering in the wind as the only vivid color accent against muted grey-brown desaturated military palette, dramatic contrast lighting with strong rim light on silhouettes, grim weathered textures on stone walls and leather equipment",
        "extraImages": "face_serious.png,face_determined.png,side.png,eating.png,sitting.png,action_blade.png,fullbody.png,action_gear.png,running.png,face_scarf.png,face_angry.png",
        "worldContext": "triple-walled medieval European city, Survey Corps women's barracks with neatly made beds and blade maintenance tools, Training Corps era barracks and mess hall, view beyond the walls from atop wall guard posts, Shiganshina battle ruins, battlefield fighting alongside Eren, iconic scene of red scarf fluttering in the wind, strong yet tender atmosphere, grey and red color contrast",
        "voiceId": "sage",
        "voiceStyle": "Stoic calm young woman, minimal words, speaks Korean with quiet flat serious tone",
        "bodyType": "근육질",
        "primaryColor": "red",
        "seriesDescription": "진격의 거인의 히로인. 에렌의 소꿉친구이자 인류 최강급 전사 중 한 명. 어린 시절 에렌에게 구원받은 후 그를 지키는 것이 삶의 목적. 아커만 가문의 피로 초인적 전투 능력을 가졌으며, 항상 에렌이 준 빨간 머플러를 두르고 있다.",
        "sortOrder": 18,
    },
    {
        "name": "파워",
        "nameEn": "Power",
        "series": "체인소 맨",
        "category": "BEAUTY",
        "description": "금발 긴 머리, 머리에 빨간 뿔 2개, 날카로운 이빨",
        "promptFeatures": "young woman age 20s, long messy wavy strawberry-blonde to orange-red hair flowing wildly, two short pointed bright red devil horns protruding from top of head, sharp visible fangs in wide open yelling mouth, fierce red-yellow gradient eyes, slim tall 173cm body with long limbs, loose oversized white dress shirt with puffy sleeves partially unbuttoned, thin black necktie hanging loose, black cropped pants rolled up at ankles, white sneakers with red accents, arrogant wild aggressive hands-on-hips pose, anime style",
        "heightCm": 173,
        "bodyBuild": "173cm 마르고 날씬한 체형, 긴 팔다리, 가는 허리",
        "faceFeatures": "긴 헝클어진 딸기금발 머리, 빨간-노란 눈, 날카로운 송곳니, 거만한 표정",
        "costumeDesc": "하얀 와이셔츠에 검은 넥타이, 검은 바지, 가끔 가슴까지 단추 풀림",
        "distinctMarks": "머리 위 빨간 뿔 2개, 날카로운 송곳니, 거만하고 야생적인 표정",
        "veoPrompt": "173cm slim tall woman age 20s, long messy strawberry blonde hair, two red curved horns on head, red-yellow eyes, sharp fangs, wild arrogant expression, white shirt loose black tie unbuttoned, black pants",
        # artStyle(KR): 어둡고 거친 그리티한 톤, MAPPA 높은 작화력, 붉은 피 무기 이펙트, 거만한 코믹 표정, 어두운 도시+붉은 대비
        "artStyle": "MAPPA Chainsaw Man style, dark gritty urban aesthetic with high-fidelity character animation, Power's sharp red horns and slim silhouette rendered with dynamic energy, Blood Fiend ability depicted as vivid crimson blood morphing into weapons with fluid splatter effects, rich arrogant comedic facial expressions in daily life scenes, dark nighttime Tokyo cityscape backgrounds with harsh artificial lighting, bold red accents contrasting against desaturated cool urban tones, Fujimoto's cinematic panel composition translated into dynamic camera work",
        "extraImages": "fullbody.png,face_smirk.png,side.png,eating.png,sitting.png,action_blood.png,running.png,fighting_stance.png,face_laugh.png,face_angry.png,face_shocked.png,face_proud.png",
        "worldContext": "modern Tokyo where devils exist, Public Safety Division office with Power's messy desk and her cat Meowy, Tokyo apartment shared with Denji, convenience stores and fast food joints, Tokyo back alley devil combat scenes, Blood Fiend ability transforming blood into weapons in battle, arrogant yet clumsy free-spirited personality, dark urban backdrop with vivid crimson blood effects",
        "voiceId": "ballad",
        "voiceStyle": "Arrogant loud young woman, bratty and dramatic, speaks Korean with self-important boasting",
        "bodyType": "슬림",
        "primaryColor": "red",
        "seriesDescription": "체인소맨에 등장하는 혈귀(피의 악마). 머리에 뿔이 나 있고, 자기 피를 무기로 만들어 싸운다. 극도로 거만하고 자기중심적이며 거짓말을 밥 먹듯 하지만 어딘가 허당인 매력적 캐릭터. 고양이 냐코를 매우 아낀다.",
        "sortOrder": 19,
    },
    {
        "name": "키르아 조르딕",
        "nameEn": "Killua Zoldyck",
        "series": "헌터x헌터",
        "category": "BEAUTY",
        "description": "은백 곱슬머리, 파란 눈, 날씬, 보라/흰 티셔츠",
        "promptFeatures": "young boy age 12, fluffy voluminous silver-white spiky hair standing up in all directions, large round bright blue cat-like eyes with slightly mischievous look, very pale white skin, slim small athletic body, oversized lavender-purple V-neck short-sleeve shirt over dark navy blue long-sleeve undershirt with turtleneck, dark grey-blue baggy shorts, purple-maroon sneakers with white soles, hands in pockets casual cool stance, anime style",
        "heightCm": 158,
        "bodyBuild": "158cm 날씬하고 민첩한 소년 체형, 가벼운 몸, 암살자 훈련된 근육",
        "faceFeatures": "은백색 복슬복슬 스파이크 머리, 밝은 파란 고양이 같은 눈, 창백한 피부, 장난꾸러기 표정",
        "costumeDesc": "보라색+흰색 긴팔 티셔츠, 짧은 반바지, 보라색 운동화",
        "distinctMarks": "은백 머리, 고양이 같은 파란 눈, 스케이트보드, 손에서 전기 방출",
        "veoPrompt": "158cm slim agile boy age 12, fluffy silver-white spiky hair, bright blue cat-like eyes, pale skin, mischievous expression, purple-white V-neck long-sleeve shirt, dark shorts, purple sneakers, carrying skateboard",
        # artStyle(KR): Madhouse 안정적 작화, 파란 번개 이펙트, 밝은 일상 vs 어두운 암살자 이중적 표현, 파란-은색 톤
        "artStyle": "Madhouse Hunter x Hunter 2011 style, clean precise linework with bright vibrant coloring and stable high-quality animation, Killua's Transmutation Nen electric ability rendered as crackling blue-white lightning arcs enveloping his body with electric glow, dual-mood visual design with bright cheerful scenes for daily adventures contrasting sharply with dark cold-eyed assassin mode, diverse world backgrounds ranging from modern cities to dense forests to fantasy game islands, cool silver-blue color tone with crisp modern digital shading, fluid agile combat movement with lightning-fast speed trails",
        "extraImages": "face_smile.png,face_mischief.png,side.png,eating_chocolate.png,skateboard.png,sitting.png,running.png,action_lightning.png,fighting_stance.png,face_cool.png,face_killer.png,face_surprised.png,fullbody.png,action_speed.png,face_happy.png",
        "worldContext": "Hunter Exam grounds with massive underground tunnels and dangerous forests, Heavens Arena 200-floor tower fighting colosseum, Yorknew City modern metropolis with auction house and luxury hotels, Greed Island fantasy game world island, Zoldyck family Kukuroo Mountain with grand estate Testing Gate and heavy-door training grounds, adventuring together with Gon, daily life of loving chocolate and snacks, blue lightning electric Nen ability effects, duality of bright everyday life and dark assassin family heritage",
        "voiceId": "coral",
        "voiceStyle": "Cool mischievous boy, calm with edge, speaks Korean with casual cleverness and hidden intensity",
        "bodyType": "소년",
        "primaryColor": "silver",
        "seriesDescription": "헌터x헌터에 등장하는 전설적 암살자 가문 조르딕 가의 셋째 아들. 어릴 때부터 암살 훈련을 받았지만, 친구 곤을 만나 자유를 갈망하게 된다. 밝고 장난기 많은 소년이지만, 전투에서는 번개처럼 빠르고 냉철한 킬러 본능을 보인다. 초콜릿을 좋아한다.",
        "sortOrder": 20,
    },
]

_bucket = os.getenv("S3_BUCKET", "eo-character-assets")
_region = os.getenv("AWS_REGION", "ap-northeast-2")
S3_BASE = f"https://{_bucket}.s3.{_region}.amazonaws.com/characters"

NAME_TO_KEY = {
    "Anya Forger": "anya-forger",
    "Monkey D. Luffy": "monkey-d-luffy",
    "Uzumaki Naruto": "uzumaki-naruto",
    "Denji": "denji",
    "Itadori Yuji": "itadori-yuji",
    "Gojo Satoru": "gojo-satoru",
    "Levi Ackerman": "levi-ackerman",
    "Eren Yeager": "eren-yeager",
    "Kamado Tanjiro": "kamado-tanjiro",
    "Kurosaki Ichigo": "kurosaki-ichigo",
    "Pikachu": "pikachu",
    "Kamado Nezuko": "kamado-nezuko",
    "Totoro": "totoro",
    "Doraemon": "doraemon",
    "Tony Tony Chopper": "tony-tony-chopper",
    "Rem": "rem",
    "Asuna Yuuki": "asuna-yuuki",
    "Mikasa Ackerman": "mikasa-ackerman",
    "Power": "power",
    "Killua Zoldyck": "killua-zoldyck",
}


async def main():
    """시드 데이터 삽입"""
    db = Prisma()
    await db.connect()

    # 기존 캐릭터 삭제 후 재삽입
    await db.character.delete_many()

    for char in CHARACTERS:
        key = NAME_TO_KEY[char["nameEn"]]
        await db.character.create(
            data={
                "name": char["name"],
                "nameEn": char["nameEn"],
                "series": char["series"],
                "category": char["category"],
                "imageUrl": f"{S3_BASE}/{key}/image.png",
                "thumbnailUrl": f"{S3_BASE}/{key}/thumbnail.png",
                "description": char["description"],
                "promptFeatures": char["promptFeatures"],
                "heightCm": char["heightCm"],
                "bodyBuild": char["bodyBuild"],
                "faceFeatures": char["faceFeatures"],
                "costumeDesc": char["costumeDesc"],
                "distinctMarks": char["distinctMarks"],
                "veoPrompt": char["veoPrompt"],
                "artStyle": char.get("artStyle", ""),
                "extraImages": char.get("extraImages", ""),
                "worldContext": char.get("worldContext", ""),
                "seriesDescription": char.get("seriesDescription", ""),
                "voiceId": char["voiceId"],
                "voiceStyle": char["voiceStyle"],
                "bodyType": char["bodyType"],
                "primaryColor": char["primaryColor"],
                "sortOrder": char["sortOrder"],
            }
        )
        print(f"  ✓ {char['name']} ({char['heightCm']}cm) → {key}")  # noqa: T201

    count = await db.character.count()
    print(f"\n총 {count}개 캐릭터 시드 완료")  # noqa: T201

    await db.disconnect()


if __name__ == "__main__":
    asyncio.run(main())
