"""캐릭터 시드 데이터 - 20캐릭터 4카테고리 (Veo 영상 생성용 신체 특징 포함)"""

from __future__ import annotations

import asyncio
import os

from prisma import Prisma

CHARACTERS = [
    # ===== 밈 / 표정 캐릭터 (MEME) =====
    {
        "name": "아냐 포저",
        "nameEn": "Anya Forger",
        "series": "스파이 패밀리",
        "category": "MEME",
        "description": "분홍 머리, 초록 눈, 작은 체구, 뿔 머리띠",
        "promptFeatures": "tiny girl age 5, shoulder-length pink hair with flower crown wreath on head, extremely large round bright green eyes taking up half the face, small open mouth showing excitement, round chubby cheeks, very small petite body, dark brown school uniform dress with gold cuff bracelets, gold pendant necklace, adorable expressive face, anime style",
        "heightCm": 99,
        "bodyBuild": "매우 작고 마른 어린아이 체형, 짧은 팔다리",
        "faceFeatures": "큰 초록색 둥근 눈, 둥근 얼굴, 작은 코와 입, 분홍색 머리카락 양갈래 번 스타일",
        "costumeDesc": "이든 아카데미 교복 - 검은색 원피스에 하얀 칼라, 빨간 리본",
        "distinctMarks": "뿔 모양 머리띠, 특유의 'ㅎ' 모양 입, 와쿠와쿠 표정",
        "veoPrompt": "99cm petite girl age 5-6, round face, huge green eyes, pink hair in two buns with horn headband, black school dress white collar red ribbon, expressive mischievous face",
        "artStyle": "밝은 파스텔 톤에 부드러운 둥근 외곽선, 캐릭터 눈이 매우 크고 동그란 디포르메 스타일, 깔끔한 디지털 채색에 그림자가 부드러움, WIT Studio 특유의 세밀한 배경(유럽풍 건물, 실내 소품)과 귀여운 코미디 이펙트(와쿠와쿠 별눈, 땀방울), 전체적으로 따뜻하고 밝은 동화책 느낌",
        "extraImages": "face_smile.png,face_waku.png,side.png,eating.png,studying.png,waving.png,running.png,jumping.png,reading.png,face_sparkle.png,face_shocked.png,face_angry.png",
        "worldContext": "냉전시대 동서분단국 오스타니아, 이든 아카데미 명문학교(고딕 양식 교사, 장미정원, 대리석 복도), 포저 가족의 따뜻한 거실과 주방, 로이드의 정신과 진료실, 베를린풍 유럽 도시 거리와 카페, 야경이 아름다운 시내 분위기, 첩보/스파이 미션 배경, 부드럽고 따뜻한 파스텔 톤",
        "seriesDescription": "스파이 패밀리는 스파이 아버지(로이드), 살인청부업자 어머니(요르), 독심술 딸(아냐)이 서로의 정체를 숨기며 가짜 가족을 이루는 코미디 액션 만화. 냉전시대 유럽풍 세계관에서 아냐의 학교생활과 가족의 비밀 임무가 유쾌하게 펼쳐진다.",
        "voiceId": "shimmer",
        "voiceStyle": "Cute little girl voice, high-pitched, excited, speaks Korean with childlike lisping and wonder",
        "bodyType": "소녀",
        "primaryColor": "pink",
        "sortOrder": 1,
    },
    {
        "name": "몽키 D. 루피",
        "nameEn": "Monkey D. Luffy",
        "series": "원피스",
        "category": "MEME",
        "description": "검은 짧은 머리, 밀짚모자, 왼쪽 눈 밑 흉터, 빨간 조끼",
        "promptFeatures": "young man age 19, very large perfectly round white eyes with tiny black dot pupils (classic One Piece eye style), short spiky messy black hair poking under large yellow straw hat with red ribbon band, small crescent scar under left eye, huge ear-to-ear toothy grin showing all teeth, open red cardigan vest with gold buttons showing bare chest with large X-shaped scar, blue denim shorts, lean tanned skin, anime style",
        "heightCm": 174,
        "bodyBuild": "마른 근육질, 고무처럼 유연한 몸, 넓은 어깨 대비 가는 허리",
        "faceFeatures": "둥글고 순진한 큰 눈, 왼쪽 눈 밑 초승달 흉터, 항상 활짝 웃는 넓은 입",
        "costumeDesc": "빨간색 오픈 조끼(단추 없이 가슴 드러냄), 파란색 반바지, 고무 샌들",
        "distinctMarks": "밀짚모자(빨간 띠), 왼쪽 눈 밑 흉터, 가슴 X자 큰 흉터",
        "veoPrompt": "174cm lean muscular young man age 19, short messy black hair, crescent scar under left eye, huge grin, straw hat with red band, open red vest showing X-scar on chest, blue shorts, rubber sandals",
        "artStyle": "굵고 과감한 검은 외곽선에 원색 위주의 화려한 채색, 캐릭터 표정이 극단적으로 과장되고(웃을 때 얼굴 전체가 입, 놀랄 때 눈이 튀어나옴) 액션 장면에서 속도선과 폭발 이펙트가 화면을 가득 채움, 오다 에이이치로 특유의 만화적 과장법으로 인체 비율이 자유롭고, 배경은 해적선/바다/열대섬 등 컬러풀하게 묘사, 전체적으로 밝고 에너지 넘치는 소년만화 스타일",
        "extraImages": "face_smile.png,face_laugh.png,side.png,eating_meat.png,eating_noodle.png,sitting.png,running.png,jumping.png,sitting_barrel.png,face_grin.png,face_yell.png,face_serious.png",
        "worldContext": "대해적시대 그랜드라인 바다, 사우전드 써니호(사자 선수상, 나무 갑판, 잔디광장, 상지의 주방, 전망대), 해적 항구 마을과 술집, 고기가 가득한 연회 테이블, 열대 섬과 해변, 워터세븐 수상도시, 와노쿠니 일본풍 성, 밀짚모자 해적단의 자유로운 모험, 밝고 화려한 색감의 만화적 세계",
        "seriesDescription": "원피스는 고무인간이 된 소년 루피가 해적왕이 되겠다는 꿈을 품고 동료들과 해적단을 꾸려 전설의 보물 원피스를 찾아 대항해시대의 바다를 모험하는 이야기. 각 섬마다 다른 문화와 적이 등장하며, 우정과 자유를 핵심 주제로 한 역대급 장편 소년만화.",
        "voiceId": "echo",
        "voiceStyle": "Energetic teenage boy, loud and cheerful, speaks Korean with carefree enthusiasm and occasional yelling",
        "bodyType": "소년",
        "primaryColor": "red",
        "sortOrder": 2,
    },
    {
        "name": "우즈마키 나루토",
        "nameEn": "Uzumaki Naruto",
        "series": "나루토",
        "category": "MEME",
        "description": "금발 스파이크, 볼 수염 자국 3줄, 주황 점프수트, 이마 보호대",
        "promptFeatures": "young man age 17, tall spiky bright golden blonde hair, vivid cerulean blue eyes with sharp determined look, three thin horizontal whisker-like marks on each cheek, dark blue metal forehead protector with engraved leaf spiral symbol tied on forehead, orange-black zip-up tracksuit jacket with high collar, athletic muscular tanned skin, confident smirk, anime style",
        "heightCm": 180,
        "bodyBuild": "다부진 운동선수 체형, 넓은 어깨, 탄탄한 근육",
        "faceFeatures": "밝은 파란 눈, 양볼에 각 3줄씩 수염 같은 자국, 금발 스파이크 머리, 넓은 이마",
        "costumeDesc": "주황+검정 트랙수트 점프수트, 검은 샌들, 이마에 나뭇잎 마을 금속 보호대",
        "distinctMarks": "양볼 수염 자국 각 3줄, 나뭇잎 이마 보호대, 오른손 붕대",
        "veoPrompt": "180cm athletic young man age 17, spiky blonde hair, blue eyes, three whisker marks each cheek, orange-black tracksuit, metal leaf village forehead protector, determined expression",
        "artStyle": "따뜻한 주황-초록 톤의 색감, 액션 장면에서 속도선과 차크라 이펙트(파란 소용돌이, 주황 꼬리 오라)가 역동적, 키시모토 마사시 특유의 날카로운 눈매와 닌자복 디자인, 배경은 일본 전통 건축+숲이 혼합된 닌자 마을, 전투 시 먼지와 폭발 이펙트가 강렬, Studio Pierrot의 장편 애니메이션 느낌",
        "extraImages": "face_smile.png,face_grin.png,side.png,eating_ramen.png,training.png,waving.png,running.png,jumping.png,sitting.png,face_determined.png,face_yell.png,face_serious.png",
        "worldContext": "나뭇잎 마을 코노하가쿠레(호카게 바위산, 닌자 아카데미, 붉은 지붕 마을 전경), 이치라쿠 라멘 가게(나무 카운터, 김 오르는 라멘 그릇, 빨간 노렌), 제7반 수련장(통나무 기둥 3개, 풀밭), 나루토 다리, 종말의 계곡 폭포, 오대 닌자마을, 일본 전통 건축과 숲이 어우러진 닌자 세계, 주황색과 초록색 자연 톤",
        "voiceId": "echo",
        "voiceStyle": "Hot-blooded teenage boy, determined and loud, speaks Korean with passionate energy and never-give-up spirit",
        "bodyType": "소년",
        "primaryColor": "orange",
        "seriesDescription": "나루토는 부모 없이 마을의 외톨이로 자란 소년 나루토가 최고의 닌자 '호카게'를 꿈꾸며 성장하는 이야기. 체내에 봉인된 구미호의 힘과 끈기로 동료들을 지키며, 닌자 세계의 전쟁과 평화를 그린 대표적 소년만화.",
        "sortOrder": 3,
    },
    {
        "name": "덴지",
        "nameEn": "Denji",
        "series": "체인소 맨",
        "category": "MEME",
        "description": "금발 헝클어진 머리, 가슴에 체인소 시동줄, 마른 체형",
        "promptFeatures": "young man age 16, messy shaggy dirty blonde-orange hair falling over forehead, small tired half-closed yellow-brown eyes, sharp jagged shark-like teeth visible in slight grin, very skinny lanky body with long limbs, wrinkled loose beige dress shirt with rolled-up sleeves, thin black necktie, black dress pants, red-white sneakers, slouching lazy posture, anime style",
        "heightCm": 170,
        "bodyBuild": "마르고 영양실조 느낌의 가는 체형, 뼈가 살짝 보이는 마른 몸",
        "faceFeatures": "날카로운 이빨, 멍한 표정, 헝클어진 더티 블론드 머리, 피곤한 눈",
        "costumeDesc": "하얀 와이셔츠에 검은 넥타이, 검은 바지, 가끔 상의 탈의",
        "distinctMarks": "가슴 중앙 체인소 시동줄 손잡이, 날카로운 송곳니",
        "veoPrompt": "170cm skinny young man age 16, messy dirty blonde hair, tired eyes, sharp jagged teeth, chainsaw pull cord on chest center, wrinkled white shirt loose black tie, black pants, wild expression",
        "artStyle": "어둡고 거친 그리티한 톤, 날것의 에너지가 느껴지는 거친 선과 채색, MAPPA 특유의 높은 작화력으로 액션 장면이 영화처럼 연출됨, 피와 체인톱이 난무하는 잔혹한 전투와 일상의 허탈한 코미디가 공존, 어두운 도쿄 뒷골목과 형광등 아래 사무실, 후지모토 타츠키의 독특한 영화적 연출",
        "extraImages": "face_smile.png,face_grin.png,side.png,fighting_stance.png,eating.png,sitting.png,fullbody.png,running.png,chainsaw_action.png,face_laugh.png,face_shocked.png,face_angry.png",
        "worldContext": "악마가 일상적으로 존재하는 현대 도쿄, 공안 대마특이과 사무실(낡은 건물, 형광등, 사무용 책상), 도쿄 뒷골목과 폐건물, 악마 출몰 현장의 파괴된 거리, 편의점과 저렴한 식당, 덴지의 허름한 아파트, 어둡고 그리티한 도시 야경, 피와 체인톱의 잔혹하면서도 유머러스한 세계, 어두운 톤에 붉은 강조색",
        "seriesDescription": "체인소맨은 빈곤한 소년 덴지가 체인톱 악마와 합체해 악마 사냥꾼이 되는 다크 액션 만화. 꿈은 소박하게 잘 먹고 여자친구 사귀는 것. 잔혹한 액션과 허탈한 유머, 예측불가한 전개가 특징.",
        "voiceId": "ash",
        "voiceStyle": "Lazy unmotivated teenage boy, low energy mumbling, speaks Korean with rough casual slang",
        "bodyType": "소년",
        "primaryColor": "yellow",
        "sortOrder": 4,
    },
    {
        "name": "이타도리 유지",
        "nameEn": "Itadori Yuji",
        "series": "주술회전",
        "category": "MEME",
        "description": "분홍/갈색 투톤 짧은 머리, 근육질, 파란 후드",
        "promptFeatures": "young man age 15, short spiky undercut hair with vivid salmon-pink top and dark brown buzzed sides, warm determined brown eyes, round friendly face with strong jaw, muscular broad-shouldered athletic build in fighting stance, dark navy blue high-collar jujutsu sorcerer uniform with purple trim lines, red scarf/hood around neck, red sneakers, energetic fighting spirit expression, anime style",
        "heightCm": 173,
        "bodyBuild": "다부진 격투가 체형, 넓은 어깨, 두꺼운 팔뚝, 탄탄한 하체",
        "faceFeatures": "갈색 눈, 짧은 언더컷 - 위는 핑크/아래는 갈색 투톤, 둥근 얼굴형",
        "costumeDesc": "검은색 주술고전 교복 상하의, 빨간 후드 또는 파란 후디",
        "distinctMarks": "분홍+갈색 투톤 헤어, 주술 각성 시 얼굴에 검은 문양",
        "veoPrompt": "173cm muscular young man age 15, undercut hair pink top brown sides, brown eyes, round face, broad shoulders, black high-collar uniform, energetic expression",
        "artStyle": "현대적 세련된 애니메이션 스타일, 날카로운 선과 보라-파란색 중심의 어두운 색감, MAPPA 특유의 3D와 2D가 혼합된 높은 퀄리티 전투 작화, 저주 에너지가 검은 연기처럼 피어오르는 이펙트, 일상 장면은 밝고 현대적인 학교 배경, 전투 장면은 어둡고 긴장감 있는 결계 내부, 캐릭터 눈에 감정이 강렬하게 드러남",
        "extraImages": "fullbody.png,face_smile.png,side_fist.png,fighting_stance.png,eating.png,sitting.png,standing_relax.png,running.png,punch_action.png,face_laugh.png,face_shocked.png,face_serious.png",
        "worldContext": "도쿄 주술고전(일본식 학교 건물, 수련 도장, 넓은 운동장), 저주가 도사리는 현대 도쿄 시내, 시부야역 지하와 번화가, 주술사 임무 현장(폐교, 폐병원, 어두운 결계 내부), 오키나와 해변, 고등학교 교실과 체육관, 밝은 일상과 어두운 저주가 공존하는 세계, 보라색과 파란색 주술 이펙트",
        "seriesDescription": "주술회전은 특급 저주 스쿠나의 손가락을 삼킨 고등학생 유지가 주술사가 되어 저주와 싸우는 다크 배틀 만화. 현대 일본을 배경으로 보이지 않는 저주가 사람을 해치고, 주술사들이 이를 퇴치하는 세계관.",
        "voiceId": "echo",
        "voiceStyle": "Bright athletic teenage boy, warm and upbeat, speaks Korean with friendly casual tone",
        "bodyType": "근육질",
        "primaryColor": "pink",
        "sortOrder": 5,
    },
    # ===== 액션 캐릭터 (ACTION) =====
    {
        "name": "고죠 사토루",
        "nameEn": "Gojo Satoru",
        "series": "주술회전",
        "category": "ACTION",
        "description": "흰 머리, 검은 안대(파란 눈), 키 큼, 검은 교복",
        "promptFeatures": "very tall man age 28, fluffy upswept snow-white spiky hair, brilliant glowing six-eyes blue irises hidden behind sleek black rectangular blindfold covering both eyes, 190cm tall lean model-like proportions with long legs, dark navy-black high-collar zip-up uniform jacket with purple geometric accents, one hand raised with index finger pointing up, handsome sharp angular features, cocky confident smirk, anime style",
        "heightCm": 190,
        "bodyBuild": "장신 마른 근육질, 190cm의 긴 팔다리, 모델 같은 비율",
        "faceFeatures": "눈부시게 밝은 하늘색/파란 눈(육안), 흰색 스파이크 머리, 날카로운 이목구비, 잘생긴 얼굴",
        "costumeDesc": "검은색 하이넥 교복 상하의, 검은 안대(눈 가림), 가끔 선글라스",
        "distinctMarks": "검은 안대로 눈을 가림, 벗으면 빛나는 파란 눈(육안), 190cm 장신",
        "veoPrompt": "190cm tall lean muscular man age 28, white spiky hair, black blindfold over brilliant blue eyes, sharp handsome face, model proportions, black high-collar uniform, cocky smirk",
        "artStyle": "현대적 세련된 애니 스타일, MAPPA의 극한 작화력으로 고죠의 무한 능력이 보라색 구체와 왜곡 공간으로 표현됨, 안대를 벗으면 빛나는 파란 눈이 화면을 지배, 전투 장면은 3D 카메라 회전과 슬로모션 연출, 일상 장면은 밝고 세련된 도쿄 배경, 파란색과 보라색이 주조색",
        "extraImages": "face_finger.png,face_smile.png,side.png,power_blue.png,eating.png,sitting.png,fullbody.png,running.png,jumping.png,face_blindfold.png,face_eyes_reveal.png,infinity_sphere.png",
        "worldContext": "도쿄 주술고전 교사(선생님 전용 라운지, 복도), 시부야 사변의 폐허가 된 번화가, 무량공처(보라색 무한 공간), 과거 주술전성기의 헤이안 시대 배경, 도쿄 타워가 보이는 고층 빌딩 옥상, 편의점에서 달콤한 디저트를 사는 일상, 최강의 주술사답게 여유로운 분위기, 선명한 파란색과 보라색 주술 이펙트",
        "voiceId": "onyx",
        "voiceStyle": "Cool confident adult man, smug and playful, speaks Korean with arrogant charm and teasing tone",
        "bodyType": "장신",
        "primaryColor": "white",
        "seriesDescription": "주술회전의 최강 캐릭터. 주술고전의 선생님으로, 육안(특수한 눈)을 가진 역대 최강의 주술사. 학생들을 가르치며 주술계의 부패를 바꾸려 하지만, 시부야 사변에서 봉인당한다. 여유롭고 장난스러운 성격이지만 전투에선 압도적.",
        "sortOrder": 6,
    },
    {
        "name": "리바이 아커만",
        "nameEn": "Levi Ackerman",
        "series": "진격의 거인",
        "category": "ACTION",
        "description": "검은 짧은 컷, 작은 키, 날카로운 눈, 조사병단 망토",
        "promptFeatures": "short man age 30s, 160cm, jet black straight undercut hair parted in middle falling over narrow sharp intimidating steel-grey eyes, cold stoic expressionless face with sharp jawline, short stature but extremely defined muscles, dark brown cropped military jacket with Wings of Freedom emblem on shoulder, billowing dark green hooded cloak, 3D maneuver gear metal boxes on hips with leather belt harness, holding grappling blade, anime style",
        "heightCm": 160,
        "bodyBuild": "160cm 단신이지만 극도로 단련된 근육, 넓은 어깨, 굵은 팔뚝과 허벅지",
        "faceFeatures": "좁고 날카로운 회색 눈, 무표정, 검은 언더컷 헤어, 날카로운 턱선",
        "costumeDesc": "갈색 조사병단 재킷, 흰 크라바트(목수건), 녹색 자유의 날개 망토, 입체기동장치",
        "distinctMarks": "160cm 단신, 흰 크라바트, 입체기동장치 벨트, 인류 최강 전사",
        "veoPrompt": "160cm short muscular man age 30s, black undercut hair, narrow sharp grey eyes, cold expression, brown military jacket Wings of Freedom, white cravat, green cloak, 3D maneuver gear belts",
        "artStyle": "어둡고 무거운 밀리터리 톤, 세밀한 음영 처리로 근육과 장비의 질감이 사실적, WIT Studio 시절의 역동적인 입체기동 액션과 MAPPA의 사실적 작화가 혼합, 거인의 피부 질감과 증기 이펙트가 공포스럽게 표현, 배경은 중세 유럽풍 성벽도시와 황량한 벌판, 전체적으로 회색-갈색-카키의 칙칙한 군사 색감",
        "extraImages": "face_arms_crossed.png,face_serious.png,side_cloak.png,action_blade.png,drinking_tea.png,studying.png,fighting_stance.png,action_attack.png,action_gear.png,face_smirk.png,face_glare.png",
        "worldContext": "3중 성벽(월 마리아/로제/시나) 안의 중세 유럽풍 도시, 조사병단 본부(석조 성, 마구간, 작전실, 식당), 성벽 위 초소와 대포, 성벽 밖 거인이 배회하는 거대한 평원과 숲, 지하 도시, 토로스트구 시가지, 입체기동장치로 건물 사이를 날아다니는 전투, 어둡고 무거운 군사적 분위기, 회색과 갈색의 칙칙한 톤",
        "voiceId": "onyx",
        "voiceStyle": "Cold stoic adult man, blunt and dry, speaks Korean with minimal emotion and sharp delivery",
        "bodyType": "소형 근육질",
        "primaryColor": "green",
        "seriesDescription": "진격의 거인은 거대한 성벽 안에서 살던 인류가 벽을 부수고 들어온 거인에 맞서 싸우는 다크 판타지. 리바이는 인류 최강 전사로, 조사병단 병장이자 입체기동장치의 달인. 차갑고 결벽증이 있지만 동료를 깊이 아끼는 캐릭터.",
        "sortOrder": 7,
    },
    {
        "name": "에렌 예거",
        "nameEn": "Eren Yeager",
        "series": "진격의 거인",
        "category": "ACTION",
        "description": "갈색 긴 머리(후반), 초록 눈, 조사병단 유니폼",
        "promptFeatures": "young man age 15 (pre-timeskip), short straight dark brown hair with center part reaching below ears, large earnest green-teal eyes, youthful round face, slim average build, tan-brown cropped military jacket with Wings of Freedom shoulder patch, white collared shirt underneath, white pants with brown leather belt straps, tall brown boots, neutral serious expression, anime style",
        "heightCm": 183,
        "bodyBuild": "183cm 마른 근육질, 긴 팔다리, 후반부 더 단단해진 체형",
        "faceFeatures": "강렬한 초록색 눈, 긴 갈색 머리(만두 묶음), 날카로운 이목구비, 결의에 찬 표정",
        "costumeDesc": "갈색 조사병단 재킷, 흰 바지, 갈색 롱부츠, 입체기동장치 벨트",
        "distinctMarks": "강렬한 초록 눈빛, 후반부 긴 머리 묶음, 손바닥 자해 흉터(거인화용)",
        "veoPrompt": "183cm lean muscular young man age 19, long dark brown hair in messy bun, fierce green eyes, sharp angular face, brown military jacket Wings of Freedom, white pants, brown boots, brooding expression",
        "artStyle": "어둡고 무거운 밀리터리 톤, 세밀한 음영과 사실적 인체 비율, WIT Studio의 역동적 카메라 워크와 MAPPA의 디테일한 표정 연기, 거인 변신 장면에서 번개와 증기 이펙트가 강렬, 후반부로 갈수록 어둡고 무거운 색감, 회색 하늘과 황토색 대지가 특징적인 종말론적 분위기",
        "extraImages": "fullbody.png,face_serious.png,side.png,action_blade.png,face_determined.png,sitting.png,running.png,fighting_stance.png,action_attack.png,face_smile.png,face_yell.png,face_angry.png",
        "worldContext": "3중 성벽 안의 중세 유럽풍 도시와 시장, 조사병단 숙소(나무 이층침대, 식당), 시간스트구 개척지, 성벽 밖 거인 영역의 폐허와 숲, 마레국의 근대 항구도시 레베리오, 파라디 섬 해안, 입체기동장치 전투와 거인 변신, 자유를 향한 투쟁의 세계, 회색빛 하늘과 황토색 대지",
        "voiceId": "ash",
        "voiceStyle": "Intense determined young man, passionate and angry, speaks Korean with fierce conviction",
        "bodyType": "근육질",
        "primaryColor": "brown",
        "seriesDescription": "진격의 거인의 주인공. 어머니를 거인에게 잃고 거인을 모두 구축하겠다고 맹세한 소년. 자신도 거인으로 변신하는 능력을 갖게 되며, 이야기가 진행될수록 자유의 의미와 전쟁의 비극을 다루는 복잡한 캐릭터.",
        "sortOrder": 8,
    },
    {
        "name": "카마도 탄지로",
        "nameEn": "Kamado Tanjiro",
        "series": "귀멸의 칼날",
        "category": "ACTION",
        "description": "적갈색 머리, 이마 흉터/자국, 큰 귀걸이, 녹흑 격자 하오리",
        "promptFeatures": "young man age 15, short wavy dark reddish-burgundy hair with bright red gradient tips swept to the right, large gentle warm burgundy-red eyes with kind expression, prominent dark red burn scar covering left forehead and reaching to eyebrow, small hanafuda flower card earrings dangling from both ears, open green-and-black checkered square pattern haori coat, black demon slayer uniform underneath with white belt, white leg wrappings, brown boots, holding katana sword, determined gentle smile, anime style",
        "heightCm": 165,
        "bodyBuild": "165cm 균형 잡힌 소년 체형, 검술 수련으로 다져진 탄탄한 몸",
        "faceFeatures": "적갈색(버건디) 짧은 머리, 이마 왼쪽 큰 흉터/화상 자국, 붉은 갈색 부드러운 눈, 선한 표정",
        "costumeDesc": "녹색+검정 바둑판 격자무늬 하오리(겉옷), 검은 대원복, 등에 나무상자",
        "distinctMarks": "이마 왼쪽 큰 흉터, 해바라기 카드(하나후다) 귀걸이, 등에 네즈코 상자",
        "veoPrompt": "165cm young man age 15, dark reddish-burgundy hair with red tips, burn scar on left forehead, gentle brown eyes, green-black checkered haori over black uniform, hanafuda earrings, wooden box on back",
        "artStyle": "ufotable 특유의 극한 영상미, 물의 호흡 검술이 파란 물결 이펙트로 화면을 감싸고, 불의 신악 에너지는 붉은 불꽃으로 표현, CG와 2D가 완벽하게 융합된 전투 장면, 캐릭터 의상의 일본 전통 무늬(격자, 마잎)가 세밀하게 묘사, 배경은 다이쇼 시대 일본의 산속/마을/열차, 밤 장면이 많아 달빛과 등불의 따뜻한 조명",
        "extraImages": "fullbody.png,face_smile.png,side.png,action_water.png,eating.png,sitting.png,walking_box.png,fighting_stance.png,action_slash.png,face_serious.png,face_determined.png,face_fire.png",
        "worldContext": "다이쇼 시대(1912-1926) 일본, 운젠 산속 탄지로 가족의 오두막(눈 덮인 산, 숯가마), 귀살대 나비저택(일본식 다다미 치료실, 정원), 무한열차(증기기관차 내부, 붉은 좌석), 유곽 요시와라(화려한 등불, 붉은 거리), 도검 대장장이 마을(온천, 안개 낀 산), 등나무 꽃이 핀 최종선별 산, 일본 전통 건축과 대나무숲, 보라색과 물빛 이펙트",
        "voiceId": "coral",
        "voiceStyle": "Kind gentle teenage boy, warm and sincere, speaks Korean with polite earnest tone",
        "bodyType": "소년",
        "primaryColor": "green",
        "seriesDescription": "귀멸의 칼날은 가족을 귀신에게 잃은 소년 탄지로가 귀신이 되어버린 여동생 네즈코를 인간으로 되돌리기 위해 귀살대(귀신 사냥꾼)가 되어 싸우는 이야기. 다이쇼 시대 일본을 배경으로 검술과 호흡법으로 귀신을 베는 화려한 액션이 특징.",
        "sortOrder": 9,
    },
    {
        "name": "쿠로사키 이치고",
        "nameEn": "Kurosaki Ichigo",
        "series": "블리치",
        "category": "ACTION",
        "description": "주황 스파이크 머리, 키 큼, 검은 사신 복장(시해)",
        "promptFeatures": "tall young man age 17, wild tall spiky bright orange hair glowing with highlights, intense narrow brown eyes with heavy brow perpetual scowl, tall 181cm lean muscular build, glowing spiritual energy aura around hands, serious fierce annoyed expression, anime style",
        "heightCm": 181,
        "bodyBuild": "181cm 장신 마른 근육질, 긴 팔다리, 전투형 체형",
        "faceFeatures": "밝은 주황색 스파이크 머리, 갈색 눈, 항상 찡그린 표정, 날카로운 이목구비",
        "costumeDesc": "검은색 사신 복장(시하쿠쇼) - 검은 기모노+하카마, 흰 띠, 등에 거대한 참월도",
        "distinctMarks": "눈에 띄는 주황 머리, 등의 거대한 참월도(잔파쿠토), 항상 찡그린 표정",
        "veoPrompt": "181cm tall lean muscular young man age 17, spiky bright orange hair, brown eyes perpetual scowl, black shinigami robe kimono and hakama white obi, massive cleaver sword on back",
        "artStyle": "클래식 소년만화 스타일의 굵은 선과 역동적 포즈, Studio Pierrot 특유의 깔끔한 셀 애니메이션, 참월도(거대한 검)를 휘두를 때 검은 영압 이펙트와 파란 빛줄기가 화면을 가름, 사신 복장의 검은색과 주황 머리의 강한 색 대비, 소울 소사이어티의 하얀 일본식 성곽과 현대 일본 학교가 교차하는 이중 세계관 배경",
        "extraImages": "action_sword.png,face_serious.png,side.png,action_slash.png,eating.png,sitting.png,fullbody.png,running.png,action_attack.png,face_smile.png,face_yell.png,face_hollow_mask.png",
        "worldContext": "카라쿠라 마을(현대 일본 주택가, 쿠로사키 의원 건물), 소울 소사이어티 세이레이테이(하얀 벽의 일본식 성곽도시, 13번대 대오 건물, 벚꽃 정원), 우에코 문도(끝없는 사막과 하얀 달), 가짜 카라쿠라 마을 결전장, 천주겐큐(거대한 수정 궁전), 사신 나비와 영압 이펙트, 일본 전통과 영혼 세계가 혼합된 분위기, 검은색과 하얀색 대비에 파란 영압",
        "voiceId": "ash",
        "voiceStyle": "Grumpy tough teenage boy, irritated but caring, speaks Korean with reluctant cool attitude",
        "bodyType": "장신",
        "primaryColor": "orange",
        "seriesDescription": "블리치는 유령을 볼 수 있는 고등학생 이치고가 사신(죽은 영혼을 인도하는 존재)의 힘을 얻어 악령 할로우와 싸우는 소년만화. 현실 세계와 영혼 세계(소울 소사이어티)를 오가며, 거대한 검으로 싸우는 화려한 배틀이 특징.",
        "sortOrder": 10,
    },
    # ===== 귀여운 캐릭터 (CUTE) =====
    {
        "name": "피카츄",
        "nameEn": "Pikachu",
        "series": "포켓몬",
        "category": "CUTE",
        "description": "노란 몸, 빨간 볼, 번개 꼬리, 뾰족한 귀(검은 끝)",
        "promptFeatures": "small chubby yellow electric mouse creature, bright yellow fur, two red circular cheek pouches, large perfectly round shiny black eyes, small triangular black nose, wide happy open mouth, long pointed ears with black tips, zigzag lightning bolt shaped flat yellow tail with brown base, two brown horizontal stripes on back, short stubby arms and feet with no fingers, round plump body, cheerful excited pose, anime style",
        "heightCm": 40,
        "bodyBuild": "40cm 작고 통통한 설치류 체형, 짧은 팔다리, 둥근 몸통",
        "faceFeatures": "큰 둥근 검은 눈, 빨간 동그란 볼 주머니, 작은 입, 뾰족한 귀(끝이 검은색)",
        "costumeDesc": "없음 - 노란색 털이 전신을 덮음, 갈색 줄무늬가 등에 2개",
        "distinctMarks": "번개 모양 꼬리(노란색), 빨간 볼, 뾰족한 귀 검은 끝",
        "veoPrompt": "40cm chubby yellow rodent, round body, big black eyes, red cheek pouches, pointed ears black tips, lightning bolt tail brown base, two brown back stripes, yellow fur, cheerful expression",
        "artStyle": "단순하고 깔끔한 외곽선에 밝은 원색 위주의 채색, 캐릭터가 둥글고 귀엽게 디포르메되어 아이부터 어른까지 친숙한 디자인, 배경은 밝고 화사한 자연풍경(초원, 숲, 해변)이 주를 이루고, 전투 장면에서 노란 전기 스파크 이펙트가 시원하게 표현, 전체적으로 밝고 건강한 어린이 애니메이션 느낌",
        "extraImages": "face_smile.png,face_happy.png,face_wink.png,side.png,eating.png,sleeping.png,running.png,jumping.png,action_thunder.png,sitting.png,waving.png,dancing.png,face_angry.png,face_surprised.png,face_love.png,face_cry.png,face_cool.png",
        "worldContext": "포켓몬 세계 관동지방, 초록빛 풀밭과 키 큰 풀숲(야생 포켓몬 출현), 포켓몬 센터(빨간 지붕, 간호순 카운터), 포켓몬 체육관(배틀 필드), 오박사 연구소, 사토시의 어깨 위나 옆에서 함께 달리기, 해변과 꽃밭, 캠프파이어와 별하늘, 밝고 화사한 자연 풍경, 노란색과 초록색 중심의 생동감 있는 색감",
        "voiceId": "shimmer",
        "voiceStyle": "Tiny cute creature, very high-pitched squeaky, speaks Korean in adorable short phrases with bright energy",
        "bodyType": "동물",
        "primaryColor": "yellow",
        "seriesDescription": "포켓몬은 다양한 몬스터(포켓몬)를 잡아 훈련시키고 배틀하는 세계관의 이야기. 피카츄는 주인공 사토시의 파트너 전기 타입 포켓몬으로, 세계에서 가장 유명한 캐릭터 중 하나. 10만볼트 전기 공격이 특기.",
        "sortOrder": 11,
    },
    {
        "name": "카마도 네즈코",
        "nameEn": "Kamado Nezuko",
        "series": "귀멸의 칼날",
        "category": "CUTE",
        "description": "긴 검은 머리(분홍 끝), 입에 대나무, 분홍 기모노",
        "promptFeatures": "young girl age 14, very long straight black hair reaching below waist with gradient orange-pink tips at the ends, large round bright pink eyes with vertical slit demon pupils, small green bamboo muzzle/gag held in mouth by red string, small round gentle face, petite slender body, pink kimono with geometric hemp leaf (asanoha) pattern, dark maroon-checkered obi belt, white haori jacket with pink lining draped over shoulders, dark leg wrappings, wooden geta sandals, gentle shy expression, anime style",
        "heightCm": 153,
        "bodyBuild": "153cm 작고 가냘픈 소녀 체형, 가는 허리, 작은 체구",
        "faceFeatures": "분홍색 세로 동공 눈, 긴 검은 머리(끝이 주황-분홍), 입에 대나무 재갈, 작은 얼굴",
        "costumeDesc": "분홍색 마 잎 무늬 기모노, 검은색+주황색 안감 하오리, 분홍 띠, 나무 게타",
        "distinctMarks": "입에 물고 있는 대나무 재갈, 머리 끝 주황-분홍 그라데이션, 분홍 눈",
        "veoPrompt": "153cm petite girl age 14, long black hair with orange-pink gradient tips, pink slit-pupil eyes, bamboo muzzle in mouth, pink kimono hemp leaf pattern, black haori orange lining, wooden geta",
        "artStyle": "ufotable의 극한 영상미, 네즈코의 폭혈(피를 불태우는 능력)이 선명한 분홍색 불꽃으로 아름답게 표현, 기모노의 마잎 무늬와 대나무 재갈이 세밀하게 묘사, 귀신 모드에서 눈의 세로 동공과 이마의 뿔이 신비로운 분위기, 따뜻한 분홍-주황 색감과 달빛의 푸른 조명이 공존",
        "extraImages": "fullbody.png,face_smile.png,side.png,action_fire.png,eating.png,sitting_box.png,walking.png,sitting.png,action_kick.png,face_determined.png,face_demon.png",
        "worldContext": "다이쇼 시대 일본, 탄지로의 등에 업힌 대나무 상자(낮에 잠자는 공간), 나비저택의 다다미 방과 정원, 무한열차 객실 내부, 유곽 요시와라의 화려한 거리(꽃무늬 기모노, 등불), 햇빛 아래 등나무 꽃밭, 밤의 숲과 달빛, 오빠를 지키는 따뜻하고 보호적인 분위기, 분홍색 폭혈 이펙트와 따뜻한 색감",
        "voiceId": "nova",
        "voiceStyle": "Quiet gentle girl, soft muffled voice, speaks Korean in very short shy whispers",
        "bodyType": "소녀",
        "primaryColor": "pink",
        "seriesDescription": "귀멸의 칼날의 히로인이자 탄지로의 여동생. 귀신에게 물려 귀신이 되었지만 인간의 마음을 잃지 않은 유일한 존재. 낮에는 대나무 상자에서 잠자고, 밤에는 오빠를 지키며 싸운다. 입에 물고 있는 대나무 재갈이 트레이드마크.",
        "sortOrder": 12,
    },
    {
        "name": "토토로",
        "nameEn": "Totoro",
        "series": "이웃집 토토로",
        "category": "CUTE",
        "description": "회색 큰 몸, 둥근 배, 큰 입, 뾰족한 귀, 짧은 꼬리",
        "promptFeatures": "massive round egg-shaped grey forest spirit creature, dark grey fur on top and sides, large cream-yellow belly with dark grey chevron/arrow pattern markings, huge wide mouth stretching ear to ear, large round white eyes with small black pupils, long grey whiskers, two tall pointed cat-like ears on top, tiny stubby arms with grey claws, short stubby legs, small pointed tail, sitting next to small child with straw hat, gentle calm expression, Studio Ghibli anime style",
        "heightCm": 200,
        "bodyBuild": "200cm 거대한 둥근 체형, 배가 크고 볼록한 달걀형, 짧은 팔다리",
        "faceFeatures": "거대한 둥근 눈(흰자 많음), 넓은 입(귀까지 찢어진), 둥근 코, 긴 수염",
        "costumeDesc": "없음 - 회색 털이 전신을 덮음, 배는 흰색/크림색에 갈색 V자 무늬",
        "distinctMarks": "거대한 둥근 몸, 배의 V자 무늬, 뾰족한 큰 귀, 우산 들기",
        "veoPrompt": "200cm massive round grey forest spirit, egg-shaped body, white belly grey chevron markings, huge mouth ear to ear, round white eyes, pointed ears, stubby limbs, short tail, grey fur, holding leaf umbrella",
        "artStyle": "미야자키 하야오 감독의 수채화풍 따뜻한 색감, 붓 터치가 살아있는 부드러운 외곽선, 배경이 한 폭의 풍경화처럼 세밀하게 그려짐(나뭇잎 하나하나, 풀잎의 흔들림, 구름의 움직임), 캐릭터는 단순하고 둥글게 디자인되어 배경과 대비, 전체적으로 초록-갈색-하늘색의 자연 색감, 향수와 따뜻함이 느껴지는 지브리 특유의 서정적 분위기",
        "extraImages": "fullbody.png,face_smile.png,side.png,umbrella.png,eating.png,sitting.png,walking.png,dancing.png,playing_ocarina.png,face_surprised.png,face_yell.png,face_laugh.png",
        "worldContext": "1950년대 일본 사이타마현 시골 마을, 사츠키와 메이의 낡은 목조 주택(삐걱거리는 마루, 먼지 날리는 다락방), 거대한 녹나무(토토로가 사는 나무 구멍), 비 오는 버스 정류장(빨간 우산, 고양이 버스), 논밭과 시냇물, 벼 이삭이 흔들리는 여름 들판, 별이 쏟아지는 밤하늘, 지브리 특유의 따뜻하고 향수 어린 자연 풍경, 초록과 흙빛의 수채화 톤",
        "voiceId": "fable",
        "voiceStyle": "Deep rumbling gentle giant, slow and warm, speaks Korean with low calm comforting tone",
        "bodyType": "대형 동물",
        "primaryColor": "grey",
        "seriesDescription": "이웃집 토토로는 시골로 이사 온 두 자매가 숲속의 거대한 정령 토토로를 만나 신비로운 경험을 하는 이야기. 스튜디오 지브리의 대표작으로, 일본 시골의 자연과 어린 시절의 순수함을 그린 따뜻한 판타지. 토토로는 회색 거대 생물로 우산을 좋아한다.",
        "sortOrder": 13,
    },
    {
        "name": "도라에몽",
        "nameEn": "Doraemon",
        "series": "도라에몽",
        "category": "CUTE",
        "description": "파란 둥근 몸, 흰 배, 빨간 코, 목에 방울, 동그란 손",
        "promptFeatures": "round spherical blue robotic cat, bright blue body, white round face and white belly area, large oval white eyes with small black dot pupils looking upward happily, small round red nose in center, wide open laughing mouth showing red tongue, six long black whiskers three on each side, no ears (flat round head), red collar with large round golden yellow bell hanging, round white sphere hands without any fingers, short stubby blue legs, semi-circular 4D pocket on white belly, cheerful laughing pose, classic Fujiko anime style",
        "heightCm": 129,
        "bodyBuild": "129cm 둥글고 통통한 로봇 고양이 체형, 짧은 팔다리, 완벽한 구 형태",
        "faceFeatures": "큰 둥근 흰 눈(검은 점 눈동자), 빨간 둥근 코, 흰 얼굴, 긴 수염 6개",
        "costumeDesc": "없음 - 파란 외피가 전신, 흰 배, 빨간 목걸이에 노란 방울, 배에 4D주머니",
        "distinctMarks": "귀 없음(쥐가 갉아먹음), 4D주머니, 빨간 코, 노란 방울, 동그란 흰 손",
        "veoPrompt": "129cm round blue robotic cat, spherical body, white face and belly, round white eyes black pupils, red nose, six whiskers, no ears, red collar yellow bell, 4D pocket on belly, round white fingerless hands",
        "artStyle": "후지코 F. 후지오 특유의 극도로 단순한 둥근 외곽선, 캐릭터가 원과 타원으로만 구성된 미니멀한 디자인, 밝은 원색(파랑, 흰색, 빨강) 위주의 단순 채색, 배경도 깔끔한 선으로 정리된 일본 주택가와 학교, 전체적으로 밝고 친근한 어린이 만화 느낌, 미래 도구가 등장할 때 반짝이는 이펙트",
        "extraImages": "face_smile.png,face_happy.png,face_wink.png,side.png,eating.png,sleeping.png,running.png,jumping.png,action_pocket.png,sitting.png,waving.png,dancing.png,face_angry.png,face_surprised.png,face_love.png,face_cry.png,face_cool.png,fullbody.png",
        "worldContext": "현대 일본 도쿄 교외 주택가, 노비타의 2층 방(책상, 벽장에서 나오는 타임머신), 뒷산 빈터(토관 3개가 놓인 놀이터, 방과후 아지트), 학교 교실과 운동장, 22세기 미래 백화점, 4차원 주머니에서 나오는 신기한 도구들(대나무 헬리콥터, 어디로든 문), 평범한 일본 주택가의 일상적이고 따뜻한 분위기, 밝고 단순한 파스텔 색감",
        "voiceId": "coral",
        "voiceStyle": "Friendly round robot, slightly nasal mid-pitch, speaks Korean with patient helpful explanations",
        "bodyType": "로봇",
        "primaryColor": "blue",
        "seriesDescription": "도라에몽은 22세기 미래에서 온 고양이형 로봇이 무능한 소년 노비타를 도와주는 일본 국민 만화. 배에 달린 4차원 주머니에서 어디로든 문, 타임머신 등 신기한 미래 도구를 꺼내 문제를 해결한다. 50년 넘게 사랑받는 일본 대표 캐릭터.",
        "sortOrder": 14,
    },
    {
        "name": "토니토니 쵸파",
        "nameEn": "Tony Tony Chopper",
        "series": "원피스",
        "category": "CUTE",
        "description": "작은 순록, 갈색 털, 분홍 모자(X표시), 파란 코",
        "promptFeatures": "tiny adorable reindeer creature standing upright on two legs, round chubby light brown fur body, very large round shiny black eyes with innocent look, small bright blue round nose, wide happy open mouth, two small brown antler horns poking out from sides of oversized pink top hat with large white X cross mark on front, red ribbon tied around hat, wearing small red shorts, tiny hooves as hands, short stubby legs, happy cute excited expression, One Piece anime style",
        "heightCm": 90,
        "bodyBuild": "90cm 작은 순록이 직립한 체형, 둥글고 통통, 짧은 팔다리",
        "faceFeatures": "큰 둥근 눈, 파란색 코(특이한 코), 갈색 털, 작은 뿔 2개",
        "costumeDesc": "분홍색 큰 실크햇(흰 X자 표시), 빨간 반바지, 가끔 배낭",
        "distinctMarks": "파란 코, 분홍 X표시 모자, 작은 순록 뿔, 직립 보행",
        "veoPrompt": "90cm small reindeer standing upright, round chubby light brown fur body, big innocent eyes, blue nose, small antlers, oversized pink top hat white X mark, red shorts",
        "artStyle": "오다 에이이치로의 굵은 외곽선에 밝은 원색 채색, 쵸파는 특히 둥글고 귀엽게 디포르메되어 마스코트 같은 디자인, 기쁠 때 별눈/하트눈 등 과장된 표정 이펙트, 의사 모드에서는 진지한 표정으로 변환, 배경은 화려한 해적선과 바다, 전체적으로 밝고 에너지 넘치는 소년만화 스타일에 귀여움이 더해진 느낌",
        "extraImages": "face_smile.png,face_happy.png,side.png,eating.png,reading.png,sleeping.png,running.png,jumping.png,action_doctor.png,sitting.png,waving.png,dancing.png,face_shy.png,face_surprised.png,face_angry.png,fullbody.png",
        "worldContext": "대해적시대 그랜드라인 바다, 사우전드 써니호 의무실(약품 선반, 작은 침대, 벚꽃 무늬 커튼), 써니호 갑판과 잔디광장, 드럼 왕국(만년설 산, 히루루크의 벚꽃), 해적 항구 마을의 시장과 과일 가판대, 열대 섬 해변, 루피와 함께하는 모험, 귀엽고 작은 의사 순록의 따뜻한 세계, 밝고 화려한 색감에 분홍 벚꽃 이펙트",
        "voiceId": "shimmer",
        "voiceStyle": "Tiny timid creature, high-pitched nervous, speaks Korean with shy stuttering and occasional bravery",
        "bodyType": "동물",
        "primaryColor": "brown",
        "seriesDescription": "원피스에 등장하는 밀짚모자 해적단의 의사. 원래는 순록이지만 악마의 열매를 먹고 인간처럼 걷고 말할 수 있게 됨. 작고 귀엽지만 뛰어난 의술 실력을 가졌고, 변신 능력으로 전투에도 참여. 루피를 선장으로 따르며 만능약을 만드는 것이 꿈.",
        "sortOrder": 15,
    },
    # ===== 인기 미남/미소녀 (BEAUTY) =====
    {
        "name": "렘",
        "nameEn": "Rem",
        "series": "리제로",
        "category": "BEAUTY",
        "description": "파란 짧은 머리(한쪽 눈 가림), 메이드복, 파란 눈",
        "promptFeatures": "young woman age 18, short chin-length light sky-blue hair with right side swept over completely covering right eye, visible left eye is large round bright blue, small delicate round face with soft gentle expression, petite slender body, black-and-white French maid dress with puffy short sleeves, white frilly apron over black skirt, white maid headdress/headband with blue ribbon, white thigh-high stockings, black mary-jane shoes, multiple character reference poses shown, anime style",
        "heightCm": 154,
        "bodyBuild": "154cm 가냘프고 슬림한 소녀 체형, 가는 허리, 작은 체구",
        "faceFeatures": "짧은 하늘색/파란 머리(오른쪽 눈 가림), 보이는 왼쪽 파란 눈, 작고 귀여운 얼굴",
        "costumeDesc": "흑백 메이드복 - 검은 원피스, 흰 에이프런, 흰 머리 장식(프릴), 파란 리본",
        "distinctMarks": "한쪽 눈을 가리는 파란 앞머리, 메이드 헤드드레스, 쌍둥이(람의 자매)",
        "veoPrompt": "154cm petite slender woman age 18, short light blue hair covering right eye, left blue eye visible, gentle expression, black-white maid uniform white apron, frilly headdress blue ribbon",
        "artStyle": "라이트노벨 삽화풍의 섬세하고 투명한 채색, 파란색-보라색 파스텔 톤이 주조색, 머리카락과 메이드복의 프릴/레이스가 매우 세밀하게 묘사, 전투 장면에서 모닝스타(쇠구슬 무기)를 휘두를 때 바람과 얼음 이펙트, 로즈월 저택의 화려한 유럽풍 실내가 배경, 전체적으로 깨끗하고 몽환적인 이세계 판타지 분위기",
        "extraImages": "face_smile.png,face_shy.png,side.png,eating.png,cleaning.png,sitting.png,running.png,action_morningstar.png,face_determined.png,fullbody.png",
        "worldContext": "중세 유럽풍 이세계 루그니카 왕국, 로즈월 대저택(화려한 서양식 복도, 크리스탈 샹들리에, 넓은 주방과 세탁실), 아람 마을(돌담길, 초가지붕 집), 왕도 루그니카(성벽 도시, 왕선거 무대), 성역(마녀의 묘소, 안개 낀 숲), 렘과 람 쌍둥이 메이드의 헌신적인 일상, 마법과 마수가 존재하는 판타지 세계, 파란색과 보라색 톤의 신비로운 분위기",
        "voiceId": "nova",
        "voiceStyle": "Devoted gentle young woman, soft and caring, speaks Korean with polite devoted warmth",
        "bodyType": "소녀",
        "primaryColor": "blue",
        "seriesDescription": "리제로(Re:Zero)는 편의점에서 이세계로 소환된 소년 스바루가 죽을 때마다 특정 시점으로 되돌아가는 능력으로 소중한 사람들을 구하려는 이야기. 렘은 로즈월 저택의 쌍둥이 메이드 중 동생으로, 스바루를 깊이 사랑하는 헌신적 캐릭터. 메이드복 차림이지만 전투력도 강하다.",
        "sortOrder": 16,
    },
    {
        "name": "아스나",
        "nameEn": "Asuna Yuuki",
        "series": "소드 아트 온라인",
        "category": "BEAUTY",
        "description": "긴 갈색/주황 머리, 흰-빨간 기사 복장, 슬림 체형",
        "promptFeatures": "young woman age 18, very long flowing chestnut-orange hair reaching below waist with small braid on left side, large warm golden-hazel eyes, elegant beautiful oval face, slender athletic body with long legs, white sleeveless top with red trim, red pleated mini skirt, grey thigh-high stockings, red knee-high boots, white detached sleeves, holding thin rapier sword, confident graceful battle stance, anime style",
        "heightCm": 168,
        "bodyBuild": "168cm 슬림하고 날씬한 체형, 긴 다리, 우아한 비율",
        "faceFeatures": "긴 밤색-주황색 스트레이트 머리(허리까지), 헤이즐/갈색 눈, 아름다운 이목구비",
        "costumeDesc": "흰+빨간 혈맹기사단 유니폼 - 흰 브레스트플레이트, 빨간 미니스커트, 흰 부츠",
        "distinctMarks": "허리까지 오는 긴 밤색 머리, 레이피어 검, 우아하고 강인한 분위기",
        "veoPrompt": "168cm slender athletic woman age 18, long chestnut-orange hair to waist, hazel eyes, elegant features, white-red knight uniform chest plate, red mini skirt, white knee boots, rapier sword",
        "artStyle": "라이트노벨 삽화풍의 밝고 투명한 채색, A-1 Pictures의 깨끗한 디지털 작화, 검술 액션에서 빛나는 검 궤적(소드 스킬)이 노란-주황 빛줄기로 표현, 가상세계 아인크라드의 중세 판타지 건축과 초원 배경이 아름답게 묘사, 캐릭터 머리카락이 바람에 흩날리는 묘사가 세밀, 전체적으로 밝은 금색-흰색 톤의 판타지 로맨스 분위기",
        "extraImages": "face_smile.png,face_happy.png,fullbody.png,side.png,eating.png,sitting.png,running.png,action_sword.png,action_rapier.png,face_blush.png,face_determined.png,face_angry.png,face_gentle.png",
        "worldContext": "가상현실 VRMMORPG 아인크라드(100층 철의 성, 각 층마다 다른 테마 - 초원/사막/빙하), 22층 숲의 집(키리토와 아스나의 통나무 오두막), 1층 하지마리의 마을(중세 성벽 도시, NPC 상점), 보스룸(거대한 석조 방, 빛나는 마법진), ALO 요정 세계(나무 위 도시), 현실의 도쿄 병원과 학교, 검과 마법의 판타지 + 미래 기술의 혼합, 밝은 금색과 하얀 빛 이펙트",
        "voiceId": "nova",
        "voiceStyle": "Elegant confident young woman, clear and strong, speaks Korean with graceful authority",
        "bodyType": "슬림",
        "primaryColor": "white",
        "seriesDescription": "소드 아트 온라인(SAO)은 VR 게임에 갇힌 1만 명의 플레이어가 게임을 클리어하지 못하면 현실에서도 죽는 데스게임에 빠지는 이야기. 아스나는 게임 속 최강 여검사이자 주인공 키리토의 연인. 우아하고 강인하며 요리 실력도 뛰어나다.",
        "sortOrder": 17,
    },
    {
        "name": "미카사 아커만",
        "nameEn": "Mikasa Ackerman",
        "series": "진격의 거인",
        "category": "BEAUTY",
        "description": "검은 짧은 머리(후반), 목 빨간 머플러, 근육질, 조사병단 유니폼",
        "promptFeatures": "young woman age 19, short chin-length straight black bob-cut hair, narrow serious dark grey eyes with stoic cold expression, beautiful but stern face, toned athletic muscular body 170cm, dark red/maroon scarf wrapped around neck, tan-brown cropped military Survey Corps jacket with Wings of Freedom shoulder patch, white shirt underneath, white pants with brown leather belt straps and 3D maneuver gear harness, tall brown knee-high boots, hand on hip confident pose, anime style",
        "heightCm": 170,
        "bodyBuild": "170cm 탄탄한 근육질 여성 체형, 복근이 보이는 단련된 몸, 넓은 어깨",
        "faceFeatures": "짧은 검은 단발(보브컷), 짙은 회색 눈, 날카롭고 아름다운 이목구비, 무표정",
        "costumeDesc": "갈색 조사병단 재킷, 흰 바지, 갈색 부츠, 입체기동장치 벨트, 목에 빨간 머플러",
        "distinctMarks": "목에 항상 두른 빨간 머플러(에렌에게 받은), 무표정하지만 아름다운 얼굴",
        "veoPrompt": "170cm toned muscular woman age 19, short black bob-cut hair, deep grey eyes, stoic stern expression, brown Survey Corps jacket Wings of Freedom, white pants, brown boots, 3D gear belts, red scarf around neck",
        "artStyle": "어둡고 무거운 밀리터리 톤, 세밀한 음영으로 미카사의 단련된 근육과 입체기동장치가 사실적으로 표현, WIT Studio의 역동적 비행 액션과 MAPPA의 감정적 클로즈업 연출, 빨간 머플러가 바람에 펄럭이는 장면이 상징적, 회색-갈색의 칙칙한 색감 속에서 빨간 머플러만 선명한 대비",
        "extraImages": "face_serious.png,face_determined.png,side.png,eating.png,sitting.png,action_blade.png,fullbody.png,action_gear.png,running.png,face_scarf.png,face_angry.png",
        "worldContext": "3중 성벽 안의 중세 유럽풍 도시, 조사병단 여성 숙소(깔끔하게 정리된 침대, 검 손질 도구), 훈련병단 시절의 막사와 식당, 성벽 위 초소에서 바라보는 성벽 밖 풍경, 시간스트구 전투의 폐허, 에렌 곁에서 싸우는 전장, 빨간 머플러가 바람에 날리는 장면, 강인하면서도 애틋한 분위기, 회색과 붉은색 대비",
        "voiceId": "sage",
        "voiceStyle": "Stoic calm young woman, minimal words, speaks Korean with quiet flat serious tone",
        "bodyType": "근육질",
        "primaryColor": "red",
        "seriesDescription": "진격의 거인의 히로인. 에렌의 소꿉친구이자 인류 최강급 전사 중 한 명. 어린 시절 에렌에게 구원받은 후 그를 지키는 것이 삶의 목적. 아커만 가문의 피로 초인적 전투 능력을 가졌으며, 항상 에렌이 준 빨간 머플러를 두르고 있다.",
        "sortOrder": 18,
    },
    {
        "name": "파워",
        "nameEn": "Power",
        "series": "체인소 맨",
        "category": "BEAUTY",
        "description": "금발 긴 머리, 머리에 빨간 뿔 2개, 날카로운 이빨",
        "promptFeatures": "young woman age 20s, long messy wavy strawberry-blonde to orange-red hair flowing wildly, two short pointed bright red devil horns protruding from top of head, sharp visible fangs in wide open yelling mouth, fierce red-yellow gradient eyes, slim tall 173cm body with long limbs, loose oversized white dress shirt with puffy sleeves partially unbuttoned, thin black necktie hanging loose, black cropped pants rolled up at ankles, white sneakers with red accents, arrogant wild aggressive hands-on-hips pose, anime style",
        "heightCm": 173,
        "bodyBuild": "173cm 마르고 날씬한 체형, 긴 팔다리, 가는 허리",
        "faceFeatures": "긴 헝클어진 딸기금발 머리, 빨간-노란 눈, 날카로운 송곳니, 거만한 표정",
        "costumeDesc": "하얀 와이셔츠에 검은 넥타이, 검은 바지, 가끔 가슴까지 단추 풀림",
        "distinctMarks": "머리 위 빨간 뿔 2개, 날카로운 송곳니, 거만하고 야생적인 표정",
        "veoPrompt": "173cm slim tall woman age 20s, long messy strawberry blonde hair, two red curved horns on head, red-yellow eyes, sharp fangs, wild arrogant expression, white shirt loose black tie unbuttoned, black pants",
        "artStyle": "어둡고 거친 그리티한 톤, MAPPA의 높은 작화력으로 파워의 날카로운 뿔과 날씬한 체형이 역동적으로 표현, 혈귀 능력 사용 시 선명한 붉은 피가 무기로 변하는 이펙트, 일상 장면에서는 거만하고 코믹한 표정 연기가 풍부, 어두운 도시 배경에서 붉은색이 강하게 대비되는 스타일",
        "extraImages": "fullbody.png,face_smirk.png,side.png,eating.png,sitting.png,action_blood.png,running.png,fighting_stance.png,face_laugh.png,face_angry.png,face_shocked.png,face_proud.png",
        "worldContext": "악마가 존재하는 현대 도쿄, 공안 대마특이과 사무실(파워의 난장판 책상, 고양이 냐코), 도쿄 아파트(덴지와 함께 사는 생활), 편의점과 패스트푸드점, 도쿄 뒷골목의 악마 전투 현장, 혈귀 능력으로 피를 무기로 만드는 전투, 거만하면서도 허당인 자유로운 성격, 어두운 도시 배경에 선명한 붉은 피 이펙트",
        "voiceId": "ballad",
        "voiceStyle": "Arrogant loud young woman, bratty and dramatic, speaks Korean with self-important boasting",
        "bodyType": "슬림",
        "primaryColor": "red",
        "seriesDescription": "체인소맨에 등장하는 혈귀(피의 악마). 머리에 뿔이 나 있고, 자기 피를 무기로 만들어 싸운다. 극도로 거만하고 자기중심적이며 거짓말을 밥 먹듯 하지만 어딘가 허당인 매력적 캐릭터. 고양이 냐코를 매우 아낀다.",
        "sortOrder": 19,
    },
    {
        "name": "키르아 조르딕",
        "nameEn": "Killua Zoldyck",
        "series": "헌터x헌터",
        "category": "BEAUTY",
        "description": "은백 곱슬머리, 파란 눈, 날씬, 보라/흰 티셔츠",
        "promptFeatures": "young boy age 12, fluffy voluminous silver-white spiky hair standing up in all directions, large round bright blue cat-like eyes with slightly mischievous look, very pale white skin, slim small athletic body, oversized lavender-purple V-neck short-sleeve shirt over dark navy blue long-sleeve undershirt with turtleneck, dark grey-blue baggy shorts, purple-maroon sneakers with white soles, hands in pockets casual cool stance, anime style",
        "heightCm": 158,
        "bodyBuild": "158cm 날씬하고 민첩한 소년 체형, 가벼운 몸, 암살자 훈련된 근육",
        "faceFeatures": "은백색 복슬복슬 스파이크 머리, 밝은 파란 고양이 같은 눈, 창백한 피부, 장난꾸러기 표정",
        "costumeDesc": "보라색+흰색 긴팔 티셔츠, 짧은 반바지, 보라색 운동화",
        "distinctMarks": "은백 머리, 고양이 같은 파란 눈, 스케이트보드, 손에서 전기 방출",
        "veoPrompt": "158cm slim agile boy age 12, fluffy silver-white spiky hair, bright blue cat-like eyes, pale skin, mischievous expression, purple-white V-neck long-sleeve shirt, dark shorts, purple sneakers, carrying skateboard",
        "artStyle": "클래식 소년만화의 깔끔한 선과 밝은 채색, Madhouse 특유의 안정적인 작화, 키루아의 전기 능력(변화계 넨) 사용 시 파란 번개 이펙트가 몸을 감싸는 연출, 일상 장면은 밝고 유쾌하지만 암살자 모드에서는 눈이 날카롭게 변하는 이중적 표현, 배경은 다양한 세계(도시/숲/게임 속 섬)가 교차, 시원한 파란색-은색 톤",
        "extraImages": "face_smile.png,face_mischief.png,side.png,eating_chocolate.png,skateboard.png,sitting.png,running.png,action_lightning.png,fighting_stance.png,face_cool.png,face_killer.png,face_surprised.png,fullbody.png,action_speed.png,face_happy.png",
        "worldContext": "헌터 시험장(거대한 지하 터널, 위험한 숲), 하늘 투기장(천공 아레나, 200층 타워), 요크신시티(현대 대도시, 경매장, 고급 호텔), 그리드 아일랜드(게임 속 판타지 섬), 조르딕 가문 쿠쿠르산(거대한 저택, 시련의 문, 무거운 문 훈련장), 곤과 함께하는 모험, 초콜릿과 과자를 좋아하는 일상, 전기 번개 능력의 파란 이펙트, 밝은 일상과 어두운 암살자 가문의 이중성",
        "voiceId": "coral",
        "voiceStyle": "Cool mischievous boy, calm with edge, speaks Korean with casual cleverness and hidden intensity",
        "bodyType": "소년",
        "primaryColor": "silver",
        "seriesDescription": "헌터x헌터에 등장하는 전설적 암살자 가문 조르딕 가의 셋째 아들. 어릴 때부터 암살 훈련을 받았지만, 친구 곤을 만나 자유를 갈망하게 된다. 밝고 장난기 많은 소년이지만, 전투에서는 번개처럼 빠르고 냉철한 킬러 본능을 보인다. 초콜릿을 좋아한다.",
        "sortOrder": 20,
    },
]

_bucket = os.getenv("S3_BUCKET", "eo-character-assets")
_region = os.getenv("AWS_REGION", "ap-northeast-2")
S3_BASE = f"https://{_bucket}.s3.{_region}.amazonaws.com/characters"

NAME_TO_KEY = {
    "Anya Forger": "anya-forger",
    "Monkey D. Luffy": "monkey-d-luffy",
    "Uzumaki Naruto": "uzumaki-naruto",
    "Denji": "denji",
    "Itadori Yuji": "itadori-yuji",
    "Gojo Satoru": "gojo-satoru",
    "Levi Ackerman": "levi-ackerman",
    "Eren Yeager": "eren-yeager",
    "Kamado Tanjiro": "kamado-tanjiro",
    "Kurosaki Ichigo": "kurosaki-ichigo",
    "Pikachu": "pikachu",
    "Kamado Nezuko": "kamado-nezuko",
    "Totoro": "totoro",
    "Doraemon": "doraemon",
    "Tony Tony Chopper": "tony-tony-chopper",
    "Rem": "rem",
    "Asuna Yuuki": "asuna-yuuki",
    "Mikasa Ackerman": "mikasa-ackerman",
    "Power": "power",
    "Killua Zoldyck": "killua-zoldyck",
}


async def main():
    """시드 데이터 삽입"""
    db = Prisma()
    await db.connect()

    # 기존 캐릭터 삭제 후 재삽입
    await db.character.delete_many()

    for char in CHARACTERS:
        key = NAME_TO_KEY[char["nameEn"]]
        await db.character.create(
            data={
                "name": char["name"],
                "nameEn": char["nameEn"],
                "series": char["series"],
                "category": char["category"],
                "imageUrl": f"{S3_BASE}/{key}/image.png",
                "thumbnailUrl": f"{S3_BASE}/{key}/thumbnail.png",
                "description": char["description"],
                "promptFeatures": char["promptFeatures"],
                "heightCm": char["heightCm"],
                "bodyBuild": char["bodyBuild"],
                "faceFeatures": char["faceFeatures"],
                "costumeDesc": char["costumeDesc"],
                "distinctMarks": char["distinctMarks"],
                "veoPrompt": char["veoPrompt"],
                "artStyle": char.get("artStyle", ""),
                "extraImages": char.get("extraImages", ""),
                "worldContext": char.get("worldContext", ""),
                "seriesDescription": char.get("seriesDescription", ""),
                "voiceId": char["voiceId"],
                "voiceStyle": char["voiceStyle"],
                "bodyType": char["bodyType"],
                "primaryColor": char["primaryColor"],
                "sortOrder": char["sortOrder"],
            }
        )
        print(f"  ✓ {char['name']} ({char['heightCm']}cm) → {key}")  # noqa: T201

    count = await db.character.count()
    print(f"\n총 {count}개 캐릭터 시드 완료")  # noqa: T201

    await db.disconnect()


if __name__ == "__main__":
    asyncio.run(main())
