"""캐릭터 시드 데이터 - 20캐릭터 4카테고리 (Veo 영상 생성용 신체 특징 포함)"""

from __future__ import annotations

import asyncio
import os

from prisma import Prisma

CHARACTERS = [
    # ===== 밈 / 표정 캐릭터 (MEME) =====
    {
        "name": "아냐 포저",
        "nameEn": "Anya Forger",
        "series": "스파이 패밀리",
        "category": "MEME",
        "description": "분홍 머리, 초록 눈, 작은 체구, 뿔 머리띠",
        "promptFeatures": "young girl, pink hair in twin buns with small horn headband, green eyes, small petite body, red dress, white collar, expressive face, anime style",
        "heightCm": 99,
        "bodyBuild": "매우 작고 마른 어린아이 체형, 짧은 팔다리",
        "faceFeatures": "큰 초록색 둥근 눈, 둥근 얼굴, 작은 코와 입, 분홍색 머리카락 양갈래 번 스타일",
        "costumeDesc": "이든 아카데미 교복 - 검은색 원피스에 하얀 칼라, 빨간 리본",
        "distinctMarks": "뿔 모양 머리띠, 특유의 'ㅎ' 모양 입, 와쿠와쿠 표정",
        "veoPrompt": "99cm petite girl age 5-6, round face, huge green eyes, pink hair in two buns with horn headband, black school dress white collar red ribbon, expressive mischievous face",
        "bodyType": "소녀",
        "primaryColor": "pink",
        "sortOrder": 1,
    },
    {
        "name": "몽키 D. 루피",
        "nameEn": "Monkey D. Luffy",
        "series": "원피스",
        "category": "MEME",
        "description": "검은 짧은 머리, 밀짚모자, 왼쪽 눈 밑 흉터, 빨간 조끼",
        "promptFeatures": "young man, short black messy hair, straw hat, scar under left eye, red open vest, blue shorts, lean muscular build, wide grin, anime style",
        "heightCm": 174,
        "bodyBuild": "마른 근육질, 고무처럼 유연한 몸, 넓은 어깨 대비 가는 허리",
        "faceFeatures": "둥글고 순진한 큰 눈, 왼쪽 눈 밑 초승달 흉터, 항상 활짝 웃는 넓은 입",
        "costumeDesc": "빨간색 오픈 조끼(단추 없이 가슴 드러냄), 파란색 반바지, 고무 샌들",
        "distinctMarks": "밀짚모자(빨간 띠), 왼쪽 눈 밑 흉터, 가슴 X자 큰 흉터",
        "veoPrompt": "174cm lean muscular young man age 19, short messy black hair, crescent scar under left eye, huge grin, straw hat with red band, open red vest showing X-scar on chest, blue shorts, rubber sandals",
        "bodyType": "소년",
        "primaryColor": "red",
        "sortOrder": 2,
    },
    {
        "name": "우즈마키 나루토",
        "nameEn": "Uzumaki Naruto",
        "series": "나루토",
        "category": "MEME",
        "description": "금발 스파이크, 볼 수염 자국 3줄, 주황 점프수트, 이마 보호대",
        "promptFeatures": "young man, spiky blonde hair, blue eyes, three whisker marks on each cheek, orange and black jumpsuit, metal forehead protector with leaf symbol, athletic build, anime style",
        "heightCm": 180,
        "bodyBuild": "다부진 운동선수 체형, 넓은 어깨, 탄탄한 근육",
        "faceFeatures": "밝은 파란 눈, 양볼에 각 3줄씩 수염 같은 자국, 금발 스파이크 머리, 넓은 이마",
        "costumeDesc": "주황+검정 트랙수트 점프수트, 검은 샌들, 이마에 나뭇잎 마을 금속 보호대",
        "distinctMarks": "양볼 수염 자국 각 3줄, 나뭇잎 이마 보호대, 오른손 붕대",
        "veoPrompt": "180cm athletic young man age 17, spiky blonde hair, blue eyes, three whisker marks each cheek, orange-black tracksuit, metal leaf village forehead protector, determined expression",
        "bodyType": "소년",
        "primaryColor": "orange",
        "sortOrder": 3,
    },
    {
        "name": "덴지",
        "nameEn": "Denji",
        "series": "체인소 맨",
        "category": "MEME",
        "description": "금발 헝클어진 머리, 가슴에 체인소 시동줄, 마른 체형",
        "promptFeatures": "young man, messy dirty blonde hair, sharp teeth, chainsaw cord pull handle on chest, slim lean body, school uniform or shirtless, wild expression, anime style",
        "heightCm": 170,
        "bodyBuild": "마르고 영양실조 느낌의 가는 체형, 뼈가 살짝 보이는 마른 몸",
        "faceFeatures": "날카로운 이빨, 멍한 표정, 헝클어진 더티 블론드 머리, 피곤한 눈",
        "costumeDesc": "하얀 와이셔츠에 검은 넥타이, 검은 바지, 가끔 상의 탈의",
        "distinctMarks": "가슴 중앙 체인소 시동줄 손잡이, 날카로운 송곳니",
        "veoPrompt": "170cm skinny young man age 16, messy dirty blonde hair, tired eyes, sharp jagged teeth, chainsaw pull cord on chest center, wrinkled white shirt loose black tie, black pants, wild expression",
        "bodyType": "소년",
        "primaryColor": "yellow",
        "sortOrder": 4,
    },
    {
        "name": "이타도리 유지",
        "nameEn": "Itadori Yuji",
        "series": "주술회전",
        "category": "MEME",
        "description": "분홍/갈색 투톤 짧은 머리, 근육질, 파란 후드",
        "promptFeatures": "young man, short undercut hair with pink top and brown sides, brown eyes, muscular athletic build, blue hoodie or black jujutsu uniform, energetic expression, anime style",
        "heightCm": 173,
        "bodyBuild": "다부진 격투가 체형, 넓은 어깨, 두꺼운 팔뚝, 탄탄한 하체",
        "faceFeatures": "갈색 눈, 짧은 언더컷 - 위는 핑크/아래는 갈색 투톤, 둥근 얼굴형",
        "costumeDesc": "검은색 주술고전 교복 상하의, 빨간 후드 또는 파란 후디",
        "distinctMarks": "분홍+갈색 투톤 헤어, 주술 각성 시 얼굴에 검은 문양",
        "veoPrompt": "173cm muscular young man age 15, undercut hair pink top brown sides, brown eyes, round face, broad shoulders, black high-collar uniform, energetic expression",
        "bodyType": "근육질",
        "primaryColor": "pink",
        "sortOrder": 5,
    },
    # ===== 액션 캐릭터 (ACTION) =====
    {
        "name": "고죠 사토루",
        "nameEn": "Gojo Satoru",
        "series": "주술회전",
        "category": "ACTION",
        "description": "흰 머리, 검은 안대(파란 눈), 키 큼, 검은 교복",
        "promptFeatures": "tall man, white spiky hair, bright blue eyes hidden by black blindfold, tall lean muscular build, black high-collar uniform, confident smirk, anime style",
        "heightCm": 190,
        "bodyBuild": "장신 마른 근육질, 190cm의 긴 팔다리, 모델 같은 비율",
        "faceFeatures": "눈부시게 밝은 하늘색/파란 눈(육안), 흰색 스파이크 머리, 날카로운 이목구비, 잘생긴 얼굴",
        "costumeDesc": "검은색 하이넥 교복 상하의, 검은 안대(눈 가림), 가끔 선글라스",
        "distinctMarks": "검은 안대로 눈을 가림, 벗으면 빛나는 파란 눈(육안), 190cm 장신",
        "veoPrompt": "190cm tall lean muscular man age 28, white spiky hair, black blindfold over brilliant blue eyes, sharp handsome face, model proportions, black high-collar uniform, cocky smirk",
        "bodyType": "장신",
        "primaryColor": "white",
        "sortOrder": 6,
    },
    {
        "name": "리바이 아커만",
        "nameEn": "Levi Ackerman",
        "series": "진격의 거인",
        "category": "ACTION",
        "description": "검은 짧은 컷, 작은 키, 날카로운 눈, 조사병단 망토",
        "promptFeatures": "short man, black undercut hair, narrow sharp grey eyes, short stature but muscular, green cloak with wings of freedom emblem, white cravat, 3D maneuver gear, anime style",
        "heightCm": 160,
        "bodyBuild": "160cm 단신이지만 극도로 단련된 근육, 넓은 어깨, 굵은 팔뚝과 허벅지",
        "faceFeatures": "좁고 날카로운 회색 눈, 무표정, 검은 언더컷 헤어, 날카로운 턱선",
        "costumeDesc": "갈색 조사병단 재킷, 흰 크라바트(목수건), 녹색 자유의 날개 망토, 입체기동장치",
        "distinctMarks": "160cm 단신, 흰 크라바트, 입체기동장치 벨트, 인류 최강 전사",
        "veoPrompt": "160cm short muscular man age 30s, black undercut hair, narrow sharp grey eyes, cold expression, brown military jacket Wings of Freedom, white cravat, green cloak, 3D maneuver gear belts",
        "bodyType": "소형 근육질",
        "primaryColor": "green",
        "sortOrder": 7,
    },
    {
        "name": "에렌 예거",
        "nameEn": "Eren Yeager",
        "series": "진격의 거인",
        "category": "ACTION",
        "description": "갈색 긴 머리(후반), 초록 눈, 조사병단 유니폼",
        "promptFeatures": "young man, long brown hair tied in bun (post timeskip), green eyes, lean muscular build, brown jacket with wings of freedom, determined fierce expression, anime style",
        "heightCm": 183,
        "bodyBuild": "183cm 마른 근육질, 긴 팔다리, 후반부 더 단단해진 체형",
        "faceFeatures": "강렬한 초록색 눈, 긴 갈색 머리(만두 묶음), 날카로운 이목구비, 결의에 찬 표정",
        "costumeDesc": "갈색 조사병단 재킷, 흰 바지, 갈색 롱부츠, 입체기동장치 벨트",
        "distinctMarks": "강렬한 초록 눈빛, 후반부 긴 머리 묶음, 손바닥 자해 흉터(거인화용)",
        "veoPrompt": "183cm lean muscular young man age 19, long dark brown hair in messy bun, fierce green eyes, sharp angular face, brown military jacket Wings of Freedom, white pants, brown boots, brooding expression",
        "bodyType": "근육질",
        "primaryColor": "brown",
        "sortOrder": 8,
    },
    {
        "name": "카마도 탄지로",
        "nameEn": "Kamado Tanjiro",
        "series": "귀멸의 칼날",
        "category": "ACTION",
        "description": "적갈색 머리, 이마 흉터/자국, 큰 귀걸이, 녹흑 격자 하오리",
        "promptFeatures": "young man, dark red burgundy hair, scar/mark on forehead, hanafuda earrings, green and black checkered haori over black uniform, kind determined eyes, anime style",
        "heightCm": 165,
        "bodyBuild": "165cm 균형 잡힌 소년 체형, 검술 수련으로 다져진 탄탄한 몸",
        "faceFeatures": "적갈색(버건디) 짧은 머리, 이마 왼쪽 큰 흉터/화상 자국, 붉은 갈색 부드러운 눈, 선한 표정",
        "costumeDesc": "녹색+검정 바둑판 격자무늬 하오리(겉옷), 검은 대원복, 등에 나무상자",
        "distinctMarks": "이마 왼쪽 큰 흉터, 해바라기 카드(하나후다) 귀걸이, 등에 네즈코 상자",
        "veoPrompt": "165cm young man age 15, dark reddish-burgundy hair with red tips, burn scar on left forehead, gentle brown eyes, green-black checkered haori over black uniform, hanafuda earrings, wooden box on back",
        "bodyType": "소년",
        "primaryColor": "green",
        "sortOrder": 9,
    },
    {
        "name": "쿠로사키 이치고",
        "nameEn": "Kurosaki Ichigo",
        "series": "블리치",
        "category": "ACTION",
        "description": "주황 스파이크 머리, 키 큼, 검은 사신 복장(시해)",
        "promptFeatures": "tall young man, spiky bright orange hair, brown eyes, tall lean muscular build, black shihakusho shinigami robe, large zanpakuto sword on back, serious expression, anime style",
        "heightCm": 181,
        "bodyBuild": "181cm 장신 마른 근육질, 긴 팔다리, 전투형 체형",
        "faceFeatures": "밝은 주황색 스파이크 머리, 갈색 눈, 항상 찡그린 표정, 날카로운 이목구비",
        "costumeDesc": "검은색 사신 복장(시하쿠쇼) - 검은 기모노+하카마, 흰 띠, 등에 거대한 참월도",
        "distinctMarks": "눈에 띄는 주황 머리, 등의 거대한 참월도(잔파쿠토), 항상 찡그린 표정",
        "veoPrompt": "181cm tall lean muscular young man age 17, spiky bright orange hair, brown eyes perpetual scowl, black shinigami robe kimono and hakama white obi, massive cleaver sword on back",
        "bodyType": "장신",
        "primaryColor": "orange",
        "sortOrder": 10,
    },
    # ===== 귀여운 캐릭터 (CUTE) =====
    {
        "name": "피카츄",
        "nameEn": "Pikachu",
        "series": "포켓몬",
        "category": "CUTE",
        "description": "노란 몸, 빨간 볼, 번개 꼬리, 뾰족한 귀(검은 끝)",
        "promptFeatures": "small yellow rodent creature, red circular cheek pouches, lightning bolt shaped tail, pointed ears with black tips, big round black eyes, cute chubby body, anime style",
        "heightCm": 40,
        "bodyBuild": "40cm 작고 통통한 설치류 체형, 짧은 팔다리, 둥근 몸통",
        "faceFeatures": "큰 둥근 검은 눈, 빨간 동그란 볼 주머니, 작은 입, 뾰족한 귀(끝이 검은색)",
        "costumeDesc": "없음 - 노란색 털이 전신을 덮음, 갈색 줄무늬가 등에 2개",
        "distinctMarks": "번개 모양 꼬리(노란색), 빨간 볼, 뾰족한 귀 검은 끝",
        "veoPrompt": "40cm chubby yellow rodent, round body, big black eyes, red cheek pouches, pointed ears black tips, lightning bolt tail brown base, two brown back stripes, yellow fur, cheerful expression",
        "bodyType": "동물",
        "primaryColor": "yellow",
        "sortOrder": 11,
    },
    {
        "name": "카마도 네즈코",
        "nameEn": "Kamado Nezuko",
        "series": "귀멸의 칼날",
        "category": "CUTE",
        "description": "긴 검은 머리(분홍 끝), 입에 대나무, 분홍 기모노",
        "promptFeatures": "young girl, long black hair with orange-pink tips, bamboo muzzle in mouth, pink eyes with slit pupils, pink kimono with hemp leaf pattern, small petite body, anime style",
        "heightCm": 153,
        "bodyBuild": "153cm 작고 가냘픈 소녀 체형, 가는 허리, 작은 체구",
        "faceFeatures": "분홍색 세로 동공 눈, 긴 검은 머리(끝이 주황-분홍), 입에 대나무 재갈, 작은 얼굴",
        "costumeDesc": "분홍색 마 잎 무늬 기모노, 검은색+주황색 안감 하오리, 분홍 띠, 나무 게타",
        "distinctMarks": "입에 물고 있는 대나무 재갈, 머리 끝 주황-분홍 그라데이션, 분홍 눈",
        "veoPrompt": "153cm petite girl age 14, long black hair with orange-pink gradient tips, pink slit-pupil eyes, bamboo muzzle in mouth, pink kimono hemp leaf pattern, black haori orange lining, wooden geta",
        "bodyType": "소녀",
        "primaryColor": "pink",
        "sortOrder": 12,
    },
    {
        "name": "토토로",
        "nameEn": "Totoro",
        "series": "이웃집 토토로",
        "category": "CUTE",
        "description": "회색 큰 몸, 둥근 배, 큰 입, 뾰족한 귀, 짧은 꼬리",
        "promptFeatures": "large round grey forest spirit creature, big wide mouth with wide grin, large pointy ears, white fluffy belly with grey chevron markings, small tail, holding umbrella, anime style",
        "heightCm": 200,
        "bodyBuild": "200cm 거대한 둥근 체형, 배가 크고 볼록한 달걀형, 짧은 팔다리",
        "faceFeatures": "거대한 둥근 눈(흰자 많음), 넓은 입(귀까지 찢어진), 둥근 코, 긴 수염",
        "costumeDesc": "없음 - 회색 털이 전신을 덮음, 배는 흰색/크림색에 갈색 V자 무늬",
        "distinctMarks": "거대한 둥근 몸, 배의 V자 무늬, 뾰족한 큰 귀, 우산 들기",
        "veoPrompt": "200cm massive round grey forest spirit, egg-shaped body, white belly grey chevron markings, huge mouth ear to ear, round white eyes, pointed ears, stubby limbs, short tail, grey fur, holding leaf umbrella",
        "bodyType": "대형 동물",
        "primaryColor": "grey",
        "sortOrder": 13,
    },
    {
        "name": "도라에몽",
        "nameEn": "Doraemon",
        "series": "도라에몽",
        "category": "CUTE",
        "description": "파란 둥근 몸, 흰 배, 빨간 코, 목에 방울, 동그란 손",
        "promptFeatures": "round blue robotic cat, white belly and face, red round nose, yellow bell on red collar, round white hands without fingers, no ears, 4D pocket on belly, anime style",
        "heightCm": 129,
        "bodyBuild": "129cm 둥글고 통통한 로봇 고양이 체형, 짧은 팔다리, 완벽한 구 형태",
        "faceFeatures": "큰 둥근 흰 눈(검은 점 눈동자), 빨간 둥근 코, 흰 얼굴, 긴 수염 6개",
        "costumeDesc": "없음 - 파란 외피가 전신, 흰 배, 빨간 목걸이에 노란 방울, 배에 4D주머니",
        "distinctMarks": "귀 없음(쥐가 갉아먹음), 4D주머니, 빨간 코, 노란 방울, 동그란 흰 손",
        "veoPrompt": "129cm round blue robotic cat, spherical body, white face and belly, round white eyes black pupils, red nose, six whiskers, no ears, red collar yellow bell, 4D pocket on belly, round white fingerless hands",
        "bodyType": "로봇",
        "primaryColor": "blue",
        "sortOrder": 14,
    },
    {
        "name": "토니토니 쵸파",
        "nameEn": "Tony Tony Chopper",
        "series": "원피스",
        "category": "CUTE",
        "description": "작은 순록, 갈색 털, 분홍 모자(X표시), 파란 코",
        "promptFeatures": "small reindeer creature, brown fur, pink top hat with white X mark, blue nose, small cute body standing upright, red shorts, anime style",
        "heightCm": 90,
        "bodyBuild": "90cm 작은 순록이 직립한 체형, 둥글고 통통, 짧은 팔다리",
        "faceFeatures": "큰 둥근 눈, 파란색 코(특이한 코), 갈색 털, 작은 뿔 2개",
        "costumeDesc": "분홍색 큰 실크햇(흰 X자 표시), 빨간 반바지, 가끔 배낭",
        "distinctMarks": "파란 코, 분홍 X표시 모자, 작은 순록 뿔, 직립 보행",
        "veoPrompt": "90cm small reindeer standing upright, round chubby light brown fur body, big innocent eyes, blue nose, small antlers, oversized pink top hat white X mark, red shorts",
        "bodyType": "동물",
        "primaryColor": "brown",
        "sortOrder": 15,
    },
    # ===== 인기 미남/미소녀 (BEAUTY) =====
    {
        "name": "렘",
        "nameEn": "Rem",
        "series": "리제로",
        "category": "BEAUTY",
        "description": "파란 짧은 머리(한쪽 눈 가림), 메이드복, 파란 눈",
        "promptFeatures": "young woman, short blue hair covering right eye, blue eyes, maid outfit with white headdress, black and white maid dress with blue accents, petite slender body, gentle expression, anime style",
        "heightCm": 154,
        "bodyBuild": "154cm 가냘프고 슬림한 소녀 체형, 가는 허리, 작은 체구",
        "faceFeatures": "짧은 하늘색/파란 머리(오른쪽 눈 가림), 보이는 왼쪽 파란 눈, 작고 귀여운 얼굴",
        "costumeDesc": "흑백 메이드복 - 검은 원피스, 흰 에이프런, 흰 머리 장식(프릴), 파란 리본",
        "distinctMarks": "한쪽 눈을 가리는 파란 앞머리, 메이드 헤드드레스, 쌍둥이(람의 자매)",
        "veoPrompt": "154cm petite slender woman age 18, short light blue hair covering right eye, left blue eye visible, gentle expression, black-white maid uniform white apron, frilly headdress blue ribbon",
        "bodyType": "소녀",
        "primaryColor": "blue",
        "sortOrder": 16,
    },
    {
        "name": "아스나",
        "nameEn": "Asuna Yuuki",
        "series": "소드 아트 온라인",
        "category": "BEAUTY",
        "description": "긴 갈색/주황 머리, 흰-빨간 기사 복장, 슬림 체형",
        "promptFeatures": "young woman, long chestnut-orange hair, hazel eyes, white and red Knights of Blood uniform, slender athletic body, rapier sword, elegant beautiful face, anime style",
        "heightCm": 168,
        "bodyBuild": "168cm 슬림하고 날씬한 체형, 긴 다리, 우아한 비율",
        "faceFeatures": "긴 밤색-주황색 스트레이트 머리(허리까지), 헤이즐/갈색 눈, 아름다운 이목구비",
        "costumeDesc": "흰+빨간 혈맹기사단 유니폼 - 흰 브레스트플레이트, 빨간 미니스커트, 흰 부츠",
        "distinctMarks": "허리까지 오는 긴 밤색 머리, 레이피어 검, 우아하고 강인한 분위기",
        "veoPrompt": "168cm slender athletic woman age 18, long chestnut-orange hair to waist, hazel eyes, elegant features, white-red knight uniform chest plate, red mini skirt, white knee boots, rapier sword",
        "bodyType": "슬림",
        "primaryColor": "white",
        "sortOrder": 17,
    },
    {
        "name": "미카사 아커만",
        "nameEn": "Mikasa Ackerman",
        "series": "진격의 거인",
        "category": "BEAUTY",
        "description": "검은 짧은 머리(후반), 목 빨간 머플러, 근육질, 조사병단 유니폼",
        "promptFeatures": "young woman, short black hair (bob cut), dark grey eyes, red scarf around neck, toned muscular body, brown jacket with wings of freedom, 3D maneuver gear, serious expression, anime style",
        "heightCm": 170,
        "bodyBuild": "170cm 탄탄한 근육질 여성 체형, 복근이 보이는 단련된 몸, 넓은 어깨",
        "faceFeatures": "짧은 검은 단발(보브컷), 짙은 회색 눈, 날카롭고 아름다운 이목구비, 무표정",
        "costumeDesc": "갈색 조사병단 재킷, 흰 바지, 갈색 부츠, 입체기동장치 벨트, 목에 빨간 머플러",
        "distinctMarks": "목에 항상 두른 빨간 머플러(에렌에게 받은), 무표정하지만 아름다운 얼굴",
        "veoPrompt": "170cm toned muscular woman age 19, short black bob-cut hair, deep grey eyes, stoic stern expression, brown Survey Corps jacket Wings of Freedom, white pants, brown boots, 3D gear belts, red scarf around neck",
        "bodyType": "근육질",
        "primaryColor": "red",
        "sortOrder": 18,
    },
    {
        "name": "파워",
        "nameEn": "Power",
        "series": "체인소 맨",
        "category": "BEAUTY",
        "description": "금발 긴 머리, 머리에 빨간 뿔 2개, 날카로운 이빨",
        "promptFeatures": "young woman, long messy strawberry blonde hair, two red horns on head, sharp fangs, red-yellow eyes, slim body, white shirt with tie, blood fiend appearance, wild expression, anime style",
        "heightCm": 173,
        "bodyBuild": "173cm 마르고 날씬한 체형, 긴 팔다리, 가는 허리",
        "faceFeatures": "긴 헝클어진 딸기금발 머리, 빨간-노란 눈, 날카로운 송곳니, 거만한 표정",
        "costumeDesc": "하얀 와이셔츠에 검은 넥타이, 검은 바지, 가끔 가슴까지 단추 풀림",
        "distinctMarks": "머리 위 빨간 뿔 2개, 날카로운 송곳니, 거만하고 야생적인 표정",
        "veoPrompt": "173cm slim tall woman age 20s, long messy strawberry blonde hair, two red curved horns on head, red-yellow eyes, sharp fangs, wild arrogant expression, white shirt loose black tie unbuttoned, black pants",
        "bodyType": "슬림",
        "primaryColor": "red",
        "sortOrder": 19,
    },
    {
        "name": "키르아 조르딕",
        "nameEn": "Killua Zoldyck",
        "series": "헌터x헌터",
        "category": "BEAUTY",
        "description": "은백 곱슬머리, 파란 눈, 날씬, 보라/흰 티셔츠",
        "promptFeatures": "young boy, fluffy silver-white spiky hair, bright blue cat-like eyes, pale skin, slim athletic body, purple and white long-sleeve shirt, skateboard, mischievous expression, anime style",
        "heightCm": 158,
        "bodyBuild": "158cm 날씬하고 민첩한 소년 체형, 가벼운 몸, 암살자 훈련된 근육",
        "faceFeatures": "은백색 복슬복슬 스파이크 머리, 밝은 파란 고양이 같은 눈, 창백한 피부, 장난꾸러기 표정",
        "costumeDesc": "보라색+흰색 긴팔 티셔츠, 짧은 반바지, 보라색 운동화",
        "distinctMarks": "은백 머리, 고양이 같은 파란 눈, 스케이트보드, 손에서 전기 방출",
        "veoPrompt": "158cm slim agile boy age 12, fluffy silver-white spiky hair, bright blue cat-like eyes, pale skin, mischievous expression, purple-white V-neck long-sleeve shirt, dark shorts, purple sneakers, carrying skateboard",
        "bodyType": "소년",
        "primaryColor": "silver",
        "sortOrder": 20,
    },
]

_bucket = os.getenv("S3_BUCKET", "eo-character-assets")
_region = os.getenv("AWS_REGION", "ap-northeast-2")
S3_BASE = f"https://{_bucket}.s3.{_region}.amazonaws.com/characters"

NAME_TO_KEY = {
    "Anya Forger": "anya-forger",
    "Monkey D. Luffy": "monkey-d-luffy",
    "Uzumaki Naruto": "uzumaki-naruto",
    "Denji": "denji",
    "Itadori Yuji": "itadori-yuji",
    "Gojo Satoru": "gojo-satoru",
    "Levi Ackerman": "levi-ackerman",
    "Eren Yeager": "eren-yeager",
    "Kamado Tanjiro": "kamado-tanjiro",
    "Kurosaki Ichigo": "kurosaki-ichigo",
    "Pikachu": "pikachu",
    "Kamado Nezuko": "kamado-nezuko",
    "Totoro": "totoro",
    "Doraemon": "doraemon",
    "Tony Tony Chopper": "tony-tony-chopper",
    "Rem": "rem",
    "Asuna Yuuki": "asuna-yuuki",
    "Mikasa Ackerman": "mikasa-ackerman",
    "Power": "power",
    "Killua Zoldyck": "killua-zoldyck",
}


async def main():
    """시드 데이터 삽입"""
    db = Prisma()
    await db.connect()

    # 기존 캐릭터 삭제 후 재삽입
    await db.character.delete_many()

    for char in CHARACTERS:
        key = NAME_TO_KEY[char["nameEn"]]
        await db.character.create(
            data={
                "name": char["name"],
                "nameEn": char["nameEn"],
                "series": char["series"],
                "category": char["category"],
                "imageUrl": f"{S3_BASE}/{key}/image.png",
                "thumbnailUrl": f"{S3_BASE}/{key}/thumbnail.png",
                "description": char["description"],
                "promptFeatures": char["promptFeatures"],
                "heightCm": char["heightCm"],
                "bodyBuild": char["bodyBuild"],
                "faceFeatures": char["faceFeatures"],
                "costumeDesc": char["costumeDesc"],
                "distinctMarks": char["distinctMarks"],
                "veoPrompt": char["veoPrompt"],
                "bodyType": char["bodyType"],
                "primaryColor": char["primaryColor"],
                "sortOrder": char["sortOrder"],
            }
        )
        print(f"  ✓ {char['name']} ({char['heightCm']}cm) → {key}")  # noqa: T201

    count = await db.character.count()
    print(f"\n총 {count}개 캐릭터 시드 완료")  # noqa: T201

    await db.disconnect()


if __name__ == "__main__":
    asyncio.run(main())
